from BaseClasses import ItemClassification

BASE_OFFSET = 100000000 #Need to figure out what to set this to. The offset for Archipelago to make it unique

class ItemData:
    def __init__(self, item_id, classification, groups):
        self.groups = groups
        self.classification = classification
        self.id = None if item_id is None else item_id + BASE_OFFSET


EOS_item_table = {
    "Test Dungeon": ItemData(0, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Beach Cave": ItemData(1, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Drenched Bluff": ItemData(3, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mt. Bristle": ItemData(4, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Waterfall Cave": ItemData(6, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Apple Woods": ItemData(7, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Craggy Coast": ItemData(8, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Side Path": ItemData(9, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mt. Horn": ItemData(10, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Rock Path": ItemData(11, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Foggy Forest": ItemData(12, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Forest Path": ItemData(13, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Steam Cave": ItemData(14, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Amp Plains": ItemData(17, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Northern Desert": ItemData(20, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Quicksand Cave": ItemData(21, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Crystal Cave": ItemData(24, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Crystal Crossing": ItemData(25, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Chasm Cave": ItemData(27, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Dark Hill": ItemData(28, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Sealed Ruin": ItemData(29, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Dusk Forest": ItemData(32, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Deep Dusk Forest": ItemData(33, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Treeshroud Forest": ItemData(34, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Brine Cave": ItemData(35, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Hidden Land": ItemData(38, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Temporal Tower": ItemData(41, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mystifying Forest": ItemData(44, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Blizzard Island": ItemData(46, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Crevice Cave": ItemData(47, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Surrounded Sea": ItemData(50, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Miracle Sea": ItemData(51, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Ice Aegis Cave": ItemData(54, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mt. Travail": ItemData(62, ItemClassification.progression, ["Unique", "Dungeons"]),
    "The Nightmare": ItemData(63, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Spacial Rift": ItemData(64, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Dark Crater": ItemData(67, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Concealed Ruins": ItemData(70, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Marine Resort": ItemData(72, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Bottomless Sea": ItemData(73, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Shimmer Desert": ItemData(75, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mt. Avalanche": ItemData(77, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Giant Volcano": ItemData(79, ItemClassification.progression, ["Unique", "Dungeons"]),
    "World Abyss": ItemData(81, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Sky Stairway": ItemData(83, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mystery Jungle": ItemData(85, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Serenity River": ItemData(87, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Landslide Cave": ItemData(88, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Lush Prairie": ItemData(89, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Tiny Meadow": ItemData(90, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Labyrinth Cave": ItemData(91, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Oran Forest": ItemData(92, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Lake Afar": ItemData(93, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Happy Outlook": ItemData(94, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Mt. Mistral": ItemData(95, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Shimmer Hill": ItemData(96, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Lost Wilderness": ItemData(97, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Midnight Forest": ItemData(98, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Zero Isle North": ItemData(99, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Zero Isle East": ItemData(100, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Zero Isle West": ItemData(101, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Zero Isle South": ItemData(102, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Zero Isle Center": ItemData(103, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Destiny Tower": ItemData(104, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(105, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(106, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Oblivion Forest": ItemData(107, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Treacherous Waters": ItemData(108, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Southeastern Islands": ItemData(109, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Inferno Cave": ItemData(110, ItemClassification.progression, ["Unique", "Dungeons"]),
    "1st Station Pass": ItemData(111, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Star Cave": ItemData(123, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Murky Forest": ItemData(128, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Eastern Cave": ItemData(129, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Fortune Ravine": ItemData(130, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Barren Valley": ItemData(133, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Dark Wasteland": ItemData(136, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Temporal Tower": ItemData(137, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Dusk Forest": ItemData(139, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Spacial Cliffs": ItemData(141, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Dark Ice Mountain": ItemData(142, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Icicle Forest": ItemData(145, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Vast Ice Mountain": ItemData(146, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Southern Jungle": ItemData(149, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Boulder Quarry": ItemData(150, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Right Cave Path": ItemData(153, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Left Cave Path": ItemData(154, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Limestone Cavern": ItemData(155, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Spring Cave": ItemData(158, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(165, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(166, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(167, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(168, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(169, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(170, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(171, ItemClassification.progression, ["Unique", "Dungeons"]),
    "[M:D1]Dummy": ItemData(172, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Star Cave": ItemData(174, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Shaymin Village": ItemData(175, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Armaldo's Shelter": ItemData(176, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Luminous Spring": ItemData(177, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Hot Spring": ItemData(178, ItemClassification.progression, ["Unique", "Dungeons"]),
    "Rescue": ItemData(179, ItemClassification.progression, ["Unique", "Dungeons"]),
}