from BaseClasses import ItemClassification

#BASE_OFFSET = 100000000 #Need to figure out what to set this to. The offset for Archipelago to make it unique

class ItemData:
    def __init__(self, item_id, classification, groups, memoryoffset):
        self.groups = groups
        self.classification = classification
        self.id = None if item_id is None else item_id
        self.memoryoffset = memoryoffset


EOS_item_table = {
    "Test Dungeon": ItemData(0, ItemClassification.progression, ["Unique", "Dungeons"],0x0),
    "Beach Cave": ItemData(1, ItemClassification.progression, ["Unique", "Dungeons"],0x1),
    "Drenched Bluff": ItemData(3, ItemClassification.progression, ["Unique", "Dungeons"],0x2),
    "Mt. Bristle": ItemData(4, ItemClassification.progression, ["Unique", "Dungeons"],0x3),
    "Waterfall Cave": ItemData(6, ItemClassification.progression, ["Unique", "Dungeons"],0x4),
    "Apple Woods": ItemData(7, ItemClassification.progression, ["Unique", "Dungeons"], 0x5),
    "Craggy Coast": ItemData(8, ItemClassification.progression, ["Unique", "Dungeons"],0x6),
    "Side Path": ItemData(9, ItemClassification.progression, ["Unique", "Dungeons"],0x7),
    "Mt. Horn": ItemData(10, ItemClassification.progression, ["Unique", "Dungeons"],0x8),
    "Rock Path": ItemData(11, ItemClassification.progression, ["Unique", "Dungeons"],0x9),
    "Foggy Forest": ItemData(12, ItemClassification.progression, ["Unique", "Dungeons"],0xA),
    "Forest Path": ItemData(13, ItemClassification.progression, ["Unique", "Dungeons"],0xB),
    "Steam Cave": ItemData(14, ItemClassification.progression, ["Unique", "Dungeons"],0xC),
    "Amp Plains": ItemData(17, ItemClassification.progression, ["Unique", "Dungeons"],0XD),
    "Northern Desert": ItemData(20, ItemClassification.progression, ["Unique", "Dungeons"],0xE),
    "Quicksand Cave": ItemData(21, ItemClassification.progression, ["Unique", "Dungeons"],0xF),
    "Crystal Cave": ItemData(24, ItemClassification.progression, ["Unique", "Dungeons"],0x10),
    "Crystal Crossing": ItemData(25, ItemClassification.progression, ["Unique", "Dungeons"],0x11),
    "Chasm Cave": ItemData(27, ItemClassification.progression, ["Unique", "Dungeons"],0x12),
    "Dark Hill": ItemData(28, ItemClassification.progression, ["Unique", "Dungeons"],0x13),
    "Sealed Ruin": ItemData(29, ItemClassification.progression, ["Unique", "Dungeons"],0x14),
    "Dusk Forest": ItemData(32, ItemClassification.progression, ["Unique", "Dungeons"],0x15),
    "Deep Dusk Forest": ItemData(33, ItemClassification.progression, ["Unique", "Dungeons"],0x16),
    "Treeshroud Forest": ItemData(34, ItemClassification.progression, ["Unique", "Dungeons"],0x17),
    "Brine Cave": ItemData(35, ItemClassification.progression, ["Unique", "Dungeons"],0x18),
    "Hidden Land": ItemData(38, ItemClassification.progression, ["Unique", "Dungeons"],0x19),
    "Temporal Tower": ItemData(41, ItemClassification.progression, ["Unique", "Dungeons"],0x1A),
    "Mystifying Forest": ItemData(44, ItemClassification.progression, ["Unique", "Dungeons"],0x1B),
    "Blizzard Island": ItemData(46, ItemClassification.progression, ["Unique", "Dungeons"],0x1C),
    "Crevice Cave": ItemData(47, ItemClassification.progression, ["Unique", "Dungeons"],0x1D),
    "Surrounded Sea": ItemData(50, ItemClassification.progression, ["Unique", "Dungeons"],0x1E),
    "Miracle Sea": ItemData(51, ItemClassification.progression, ["Unique", "Dungeons"],0x1F),
    "Ice Aegis Cave": ItemData(54, ItemClassification.progression, ["Unique", "Dungeons"],0x20),
    "Mt. Travail": ItemData(62, ItemClassification.progression, ["Unique", "Dungeons"],0x21),
    "The Nightmare": ItemData(63, ItemClassification.progression, ["Unique", "Dungeons"],0x22),
    "Spacial Rift": ItemData(64, ItemClassification.progression, ["Unique", "Dungeons"],0x23),
    "Dark Crater": ItemData(67, ItemClassification.progression, ["Unique", "Dungeons"],0x24),
    "Concealed Ruins": ItemData(70, ItemClassification.progression, ["Unique", "Dungeons"],0x25),
    "Marine Resort": ItemData(72, ItemClassification.progression, ["Unique", "Dungeons"],0x26),
    "Bottomless Sea": ItemData(73, ItemClassification.progression, ["Unique", "Dungeons"],0x27),
    "Shimmer Desert": ItemData(75, ItemClassification.progression, ["Unique", "Dungeons"],0x28),
    "Mt. Avalanche": ItemData(77, ItemClassification.progression, ["Unique", "Dungeons"],0x29),
    "Giant Volcano": ItemData(79, ItemClassification.progression, ["Unique", "Dungeons"],0x2A),
    "World Abyss": ItemData(81, ItemClassification.progression, ["Unique", "Dungeons"],0x2B),
    "Sky Stairway": ItemData(83, ItemClassification.progression, ["Unique", "Dungeons"],0x2C),
    "Mystery Jungle": ItemData(85, ItemClassification.progression, ["Unique", "Dungeons"],0x2D),
    "Serenity River": ItemData(87, ItemClassification.progression, ["Unique", "Dungeons"],0x2E),
    "Landslide Cave": ItemData(88, ItemClassification.progression, ["Unique", "Dungeons"],0x2F),
    "Lush Prairie": ItemData(89, ItemClassification.progression, ["Unique", "Dungeons"],0x30),
    "Tiny Meadow": ItemData(90, ItemClassification.progression, ["Unique", "Dungeons"],0x31),
    "Labyrinth Cave": ItemData(91, ItemClassification.progression, ["Unique", "Dungeons"],0x32),
    "Oran Forest": ItemData(92, ItemClassification.progression, ["Unique", "Dungeons"],0x33),
    "Lake Afar": ItemData(93, ItemClassification.progression, ["Unique", "Dungeons"],0x34),
    "Happy Outlook": ItemData(94, ItemClassification.progression, ["Unique", "Dungeons"],0x35),
    "Mt. Mistral": ItemData(95, ItemClassification.progression, ["Unique", "Dungeons"],0x36),
    "Shimmer Hill": ItemData(96, ItemClassification.progression, ["Unique", "Dungeons"],0x37),
    "Lost Wilderness": ItemData(97, ItemClassification.progression, ["Unique", "Dungeons"],0x38),
    "Midnight Forest": ItemData(98, ItemClassification.progression, ["Unique", "Dungeons"],0x39),
    "Zero Isle North": ItemData(99, ItemClassification.progression, ["Unique", "Dungeons"],0x3A),
    "Zero Isle East": ItemData(100, ItemClassification.progression, ["Unique", "Dungeons"],0x3B),
    "Zero Isle West": ItemData(101, ItemClassification.progression, ["Unique", "Dungeons"],0x3C),
    "Zero Isle South": ItemData(102, ItemClassification.progression, ["Unique", "Dungeons"],0x3D),
    "Zero Isle Center": ItemData(103, ItemClassification.progression, ["Unique", "Dungeons"],0x3E),
    "Destiny Tower": ItemData(104, ItemClassification.progression, ["Unique", "Dungeons"],0x3F),
    "[M:D1]Dummy": ItemData(105, ItemClassification.progression, ["Unique", "Dungeons"],0x40),
    "[M:D1]Dummy": ItemData(106, ItemClassification.progression, ["Unique", "Dungeons"],0x41),
    "Oblivion Forest": ItemData(107, ItemClassification.progression, ["Unique", "Dungeons"],0x42),
    "Treacherous Waters": ItemData(108, ItemClassification.progression, ["Unique", "Dungeons"],0x43),
    "Southeastern Islands": ItemData(109, ItemClassification.progression, ["Unique", "Dungeons"],0x44),
    "Inferno Cave": ItemData(110, ItemClassification.progression, ["Unique", "Dungeons"],0x45),
    "1st Station Pass": ItemData(111, ItemClassification.progression, ["Unique", "Dungeons"],0x46),
    "Star Cave": ItemData(123, ItemClassification.progression, ["Unique", "Dungeons"],0x47),
    "Murky Forest": ItemData(128, ItemClassification.progression, ["Unique", "Dungeons"],0x48),
    "Eastern Cave": ItemData(129, ItemClassification.progression, ["Unique", "Dungeons"],0x49),
    "Fortune Ravine": ItemData(130, ItemClassification.progression, ["Unique", "Dungeons"],0x4A),
    "Barren Valley": ItemData(133, ItemClassification.progression, ["Unique", "Dungeons"],0x4B),
    "Dark Wasteland": ItemData(136, ItemClassification.progression, ["Unique", "Dungeons"],0x4C),
    "Temporal Tower": ItemData(137, ItemClassification.progression, ["Unique", "Dungeons"],0x4D),
    "Dusk Forest": ItemData(139, ItemClassification.progression, ["Unique", "Dungeons"],0x4E),
    "Spacial Cliffs": ItemData(141, ItemClassification.progression, ["Unique", "Dungeons"],0x4F),
    "Dark Ice Mountain": ItemData(142, ItemClassification.progression, ["Unique", "Dungeons"],0x50),
    "Icicle Forest": ItemData(145, ItemClassification.progression, ["Unique", "Dungeons"],0x51),
    "Vast Ice Mountain": ItemData(146, ItemClassification.progression, ["Unique", "Dungeons"],0x52),
    "Southern Jungle": ItemData(149, ItemClassification.progression, ["Unique", "Dungeons"],0x53),
    "Boulder Quarry": ItemData(150, ItemClassification.progression, ["Unique", "Dungeons"],0x54),
    "Right Cave Path": ItemData(153, ItemClassification.progression, ["Unique", "Dungeons"],0x55),
    "Left Cave Path": ItemData(154, ItemClassification.progression, ["Unique", "Dungeons"],0x56),
    "Limestone Cavern": ItemData(155, ItemClassification.progression, ["Unique", "Dungeons"],0x57),
    "Spring Cave": ItemData(158, ItemClassification.progression, ["Unique", "Dungeons"],0x58),
    "[M:D1]Dummy": ItemData(165, ItemClassification.progression, ["Unique", "Dungeons"],0x59),
    "[M:D1]Dummy": ItemData(166, ItemClassification.progression, ["Unique", "Dungeons"],0x5A),
    "[M:D1]Dummy": ItemData(167, ItemClassification.progression, ["Unique", "Dungeons"],0x5B),
    "[M:D1]Dummy": ItemData(168, ItemClassification.progression, ["Unique", "Dungeons"],0x5C),
    "[M:D1]Dummy": ItemData(169, ItemClassification.progression, ["Unique", "Dungeons"],0x5D),
    "[M:D1]Dummy": ItemData(170, ItemClassification.progression, ["Unique", "Dungeons"],0x5E),
    "[M:D1]Dummy": ItemData(171, ItemClassification.progression, ["Unique", "Dungeons"],0x5F),
    "[M:D1]Dummy": ItemData(172, ItemClassification.progression, ["Unique", "Dungeons"],0x60),
    "Star Cave": ItemData(174, ItemClassification.progression, ["Unique", "Dungeons"],0x61),
    "Shaymin Village": ItemData(175, ItemClassification.progression, ["Unique", "Dungeons"],0x62),
    "Armaldo's Shelter": ItemData(176, ItemClassification.progression, ["Unique", "Dungeons"],0x63),
    "Luminous Spring": ItemData(177, ItemClassification.progression, ["Unique", "Dungeons"],0x64),
    "Hot Spring": ItemData(178, ItemClassification.progression, ["Unique", "Dungeons"],0x65),
    "Rescue": ItemData(179, ItemClassification.progression, ["Unique", "Dungeons"],0x66),
}