from BaseClasses import Location

BASE_OFFSET = 100000000

class EOSLocation(Location):
    def __init__(self, item_id, classification, groups):
        self.groups = groups
        self.classification = classification
        self.id = None if item_id is None else item_id + BASE_OFFSET


EOS_location_table = {
    "Test Dungeon": 0,
    "Beach Cave": 1,
    "Drenched Bluff": 3,
    "Mt. Bristle": 4,
    "Waterfall Cave": 6,
    "Apple Woods": 7,
    "Craggy Coast": 8,
    "Side Path": 9,
    "Mt. Horn": 10,
    "Rock Path": 11,
    "Foggy Forest": 12,
    "Forest Path": 13,
    "Steam Cave": 14,
    "Amp Plains": 17,
    "Northern Desert": 20,
    "Quicksand Cave": 21,
    "Crystal Cave": 24,
    "Crystal Crossing": 25,
    "Chasm Cave": 27,
    "Dark Hill": 28,
    "Sealed Ruin": 29,
    "Dusk Forest": 32,
    "Deep Dusk Forest": 33,
    "Treeshroud Forest": 34,
    "Brine Cave": 35,
    "Hidden Land": 38,
    "Temporal Tower": 41,
    "Mystifying Forest": 44,
    "Blizzard Island": 46,
    "Crevice Cave": 47,
    "Surrounded Sea": 50,
    "Miracle Sea": 51,
    "Ice Aegis Cave": 54,
    "Mt. Travail": 62,
    "The Nightmare": 63,
    "Spacial Rift": 64,
    "Dark Crater": 67,
    "Concealed Ruins": 70,
    "Marine Resort": 72,
    "Bottomless Sea": 73,
    "Shimmer Desert": 75,
    "Mt. Avalanche": 77,
    "Giant Volcano": 79,
    "World Abyss": 81,
    "Sky Stairway": 83,
    "Mystery Jungle": 85,
    "Serenity River": 87,
    "Landslide Cave": 88,
    "Lush Prairie": 89,
    "Tiny Meadow": 90,
    "Labyrinth Cave": 91,
    "Oran Forest": 92,
    "Lake Afar": 93,
    "Happy Outlook": 94,
    "Mt. Mistral": 95,
    "Shimmer Hill": 96,
    "Lost Wilderness": 97,
    "Midnight Forest": 98,
    "Zero Isle North": 99,
    "Zero Isle East": 100,
    "Zero Isle West": 101,
    "Zero Isle South": 102,
    "Zero Isle Center": 103,
    "Destiny Tower": 104,
    "[M:D1]Dummy": 105,
    "[M:D1]Dummy": 106,
    "Oblivion Forest": 107,
    "Treacherous Waters": 108,
    "Southeastern Islands": 109,
    "Inferno Cave": 110,
    "1st Station Pass": 111,
    "Star Cave": 123,
    "Murky Forest": 128,
    "Eastern Cave": 129,
    "Fortune Ravine": 130,
    "Barren Valley": 133,
    "Dark Wasteland": 136,
    "Temporal Tower": 137,
    "Dusk Forest": 139,
    "Spacial Cliffs": 141,
    "Dark Ice Mountain": 142,
    "Icicle Forest": 145,
    "Vast Ice Mountain": 146,
    "Southern Jungle": 149,
    "Boulder Quarry": 150,
    "Right Cave Path": 153,
    "Left Cave Path": 154,
    "Limestone Cavern": 155,
    "Spring Cave": 158,
    "[M:D1]Dummy": 165,
    "[M:D1]Dummy": 166,
    "[M:D1]Dummy": 167,
    "[M:D1]Dummy": 168,
    "[M:D1]Dummy": 169,
    "[M:D1]Dummy": 170,
    "[M:D1]Dummy": 171,
    "[M:D1]Dummy": 172,
    "Star Cave": 174,
    "Shaymin Village": 175,
    "Armaldo's Shelter": 176,
    "Luminous Spring": 177,
    "Hot Spring": 178,
    "Rescue": 179,
}