#list of pokemon with data about the recruitment
# [pokemon_name, recruit rate, [Location], [pre_evolution, level_requirement, item_requirement], long_location, Dungeon Location]

pokemon_info =  [
    ['Bulbasaur', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Ivysaur', 0.395, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Bulbasaur', 16, False, 0], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Venusaur', 0.375, ['Mystery Jungle'], ['Ivysaur', 32, False, 1], False, ['Late']] ,
    ['Charmander', 0.577, ['Giant Volcano'], [], False, ['Late']] ,
    ['Charmeleon', 0.395, ['Giant Volcano'], ['Charmander', 16, False, 3], False, ['Late']] ,
    ['Charizard', 0.375, ['Spacial Rift'], ['Charmeleon', 36, False, 4], False, ['Late']] ,
    ['Squirtle', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Wartortle', 0.395, ['Lake Afar'], ['Squirtle', 16, False, 6], False, ['Late']] ,
    ['Blastoise', 0.375, ['Lake Afar'], ['Wartortle', 36, False, 7], False, ['Late']] ,
    ['Caterpie', 0.577, ['Apple Woods', 'Oran Forest'], [], False, ['Early', 'Early']] ,
    ['Metapod', 0.395, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', 'Happy Outlook', 'Mystery Jungle'], ['Caterpie', 7, False, 9], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Butterfree', 0.55, ['Apple Woods'], ['Metapod', 10, False, 10], False, ['Early']] ,
    ['Weedle', 0.577, ['Apple Woods'], [], False, ['Early']] ,
    ['Kakuna', 0.545, ['Apple Woods'], ['Weedle', 7, False, 12], False, ['Early']] ,
    ['Beedrill', 0.545, ['Apple Woods', 'Midnight Forest'], ['Kakuna', 10, False, 13], False, ['Early', 'Late']] ,
    ['Pidgey', 0.577, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']] ,
    ['Pidgeotto', 0.45, ['Concealed Ruins', 'World Abyss'], ['Pidgey', 18, False, 15], False, ['Late', 'Late']] ,
    ['Pidgeot', 0.395, ['Concealed Ruins', 'Mt. Mistral', 'World Abyss'], ['Pidgeotto', 36, False, 16], False, ['Late', 'Late', 'Late']] ,
    ['Rattata', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Raticate', 0.45, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Midnight Forest', 'Mystery Jungle'], ['Rattata', 20, False, 18], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Spearow', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Fearow', 0.45, ['5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail', 'Mt. Mistral'], ['Spearow', 20, False, 20], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Ekans', 0.5, ['Shimmer Desert'], [], False, ['Late']] ,
    ['Arbok', 0.375, ['Shimmer Desert'], ['Ekans', 22, False, 22], False, ['Late']] ,
    ['Pikachu', 0.577, ['Amp Plains'], ['Pichu', 0, True, 171], False, ['Early']] ,
    ['Raichu', 0.375, ['Sky Stairway'], ['Pikachu', 0, True, 24], False, ['Late']] ,
    ['Sandshrew', 0.577, ['Northern Desert', 'Shimmer Desert'], [], False, ['Early', 'Late']] ,
    ['Sandslash', 0.5, ['Northern Desert', 'Quicksand Cave', 'Shimmer Desert'], ['Sandshrew', 22, False, 26], False, ['Early', 'Early', 'Late']] ,
    ['Nidoran-F', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Nidorina', 0.5, ['Mt. Bristle', 'Labyrinth Cave'], ['Nidoran-F', 16, False, 28], False, ['Early', 'Early']] ,
    ['Nidoqueen', 0.375, ['Concealed Ruins', 'World Abyss'], ['Nidorina', 0, True, 29], False, ['Late', 'Late']] ,
    ['Nidoran-M', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Nidorino', 0.5, ['Mt. Bristle', 'Labyrinth Cave'], ['Nidoran-M', 16, False, 31], False, ['Early', 'Early']] ,
    ['Nidoking', 0.375, ['Shimmer Desert'], ['Nidorino', 0, True, 32], False, ['Late']] ,
    ['Clefairy', 0.45, ['Marine Resort'], ['Cleffa', 0, True, 172], False, ['Late']] ,
    ['Clefable', 0.375, ['Marine Resort'], ['Clefairy', 0, True, 34], False, ['Late']] ,
    ['Vulpix', 0.577, ['Sky Stairway'], [], False, ['Late']] ,
    ['Ninetales', 0.45, ['Treeshroud Forest'], ['Vulpix', 0, True, 36], False, ['Early']] ,
    ['Jigglypuff', 0.45, ['Marine Resort'], ['Igglybuff', 0, True, 173], False, ['Late']] ,
    ['Wigglytuff', 0.375, ['Marine Resort'], ['Jigglypuff', 0, True, 38], False, ['Late']] ,
    ['Zubat', 0.55, ['Ice Aegis Cave'], [], False, ['Late']] ,
    ['Golbat', 0.45, ['Ice Aegis Cave', 'Labyrinth Cave'], ['Zubat', 22, False, 40], False, ['Late', 'Early']] ,
    ['Oddish', 0.577, ['Apple Woods', 'Oran Forest', 'Happy Outlook'], [], False, ['Early', 'Early', 'Late']] ,
    ['Gloom', 0.496, ['Apple Woods'], ['Oddish', 21, False, 42], False, ['Early']] ,
    ['Vileplume', 0.375, ['Mystery Jungle'], ['Gloom', 0, True, 43], False, ['Late']] ,
    ['Paras', 0.577, ['Apple Woods'], [], False, ['Early']] ,
    ['Parasect', 0.45, ['Mt. Horn'], ['Paras', 24, False, 45], False, ['Early']] ,
    ['Venonat', 0.577, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Venomoth', 0.45, ['Mt. Horn', 'Landslide Cave', 'Mt. Mistral', 'Midnight Forest'], ['Venonat', 31, False, 47], False, ['Early', 'Early', 'Late', 'Late']] ,
    ['Diglett', 0.577, ['Shimmer Desert'], [], False, ['Late']] ,
    ['Dugtrio', 0.45, ['Shimmer Desert'], ['Diglett', 26, False, 49], False, ['Late']] ,
    ['Meowth', 0.577, ['Happy Outlook'], [], False, ['Late']] ,
    ['Persian', 0.375, ['Happy Outlook'], ['Meowth', 28, False, 51], False, ['Late']] ,
    ['Psyduck', 0.577, ['Waterfall Cave'], [], False, ['Early']] ,
    ['Golduck', 0.375, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Psyduck', 33, False, 53], False, ['Late', 'Late', 'Late']] ,
    ['Mankey', 0.577, ['Mt. Travail'], [], False, ['Late']] ,
    ['Primeape', 0.45, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Mankey', 28, False, 55], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Growlithe', 0.577, ['Giant Volcano'], [], False, ['Late']] ,
    ['Arcanine', 0.375, [], ['Growlithe', 0, True, 57], False, []] ,
    ['Poliwag', 0.5589999999999999, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']] ,
    ['Poliwhirl', 0.5, ['Lake Afar'], ['Poliwag', 25, False, 59], False, ['Late']] ,
    ['Poliwrath', 0.5, ['Lake Afar'], ['Poliwhirl', 0, True, 60], False, ['Late']] ,
    ['Abra', 0.577, ['Lost Wilderness'], [], False, ['Late']] ,
    ['Kadabra', 0.45, ['Treeshroud Forest', 'Spacial Rift', 'Lost Wilderness'], ['Abra', 16, False, 62], False, ['Early', 'Late', 'Late']] ,
    ['Alakazam', 0.375, ['Treeshroud Forest'], ['Kadabra', 0, True, 63], False, ['Early']] ,
    ['Machop', 0.577, ['Mt. Bristle', 'Labyrinth Cave', 'Final Maze'], [], False, ['Early', 'Early', 'Late']] ,
    ['Machoke', 0.45, ['Ice Aegis Cave'], ['Machop', 28, False, 65], False, ['Late']] ,
    ['Machamp', 0.395, ['Ice Aegis Cave'], ['Machoke', 0, True, 66], False, ['Late']] ,
    ['Bellsprout', 0.577, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Weepinbell', 0.395, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Bellsprout', 21, False, 68], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Victreebel', 0.375, ['Mystery Jungle'], ['Weepinbell', 0, True, 69], False, ['Late']] ,
    ['Tentacool', 0.577, ['Brine Cave'], [], False, ['Early']] ,
    ['Tentacruel', 0.45, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Tentacool', 30, False, 71], False, ['Late', 'Late', 'Late']] ,
    ['Geodude', 0.577, ['Mt. Bristle'], [], False, ['Early']] ,
    ['Graveler', 0.5, ['Crystal Cave'], ['Geodude', 25, False, 73], False, ['Early']] ,
    ['Golem', 0.5, ['Crystal Cave'], ['Graveler', 0, True, 74], False, ['Early']] ,
    ['Ponyta', 0.577, ['Giant Volcano'], [], False, ['Late']] ,
    ['Rapidash', 0.45, ['Giant Volcano'], ['Ponyta', 40, False, 76], False, ['Late']] ,
    ['Slowpoke', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Slowbro', 0.375, ['Surrounded Sea', 'Miracle Sea', 'Marine Resort', 'Bottomless Sea'], ['Slowpoke', 37, False, 78], False, ['Late', 'Late', 'Late', 'Late']] ,
    ['Magnemite', 0.577, ['Sky Stairway', 'Final Maze'], [], False, ['Late', 'Late']] ,
    ['Magneton', 0.45, ['Sky Stairway'], ['Magnemite', 30, False, 80], False, ['Late']] ,
    ['Farfetchd', 0.5589999999999999, ['Steam Cave', 'Steam Cave'], [], False, ['Early', 'Early']] ,
    ['Doduo', 0.5589999999999999, ['Mt. Bristle', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Dodrio', 0.5, ['Amp Plains'], ['Doduo', 31, False, 83], False, ['Early']] ,
    ['Seel', 0.534, ['Brine Cave'], [], False, ['Early']] ,
    ['Dewgong', 0.45, ['Brine Cave'], ['Seel', 34, False, 85], False, ['Early']] ,
    ['Grimer', 0.5589999999999999, ['Waterfall Cave'], [], False, ['Early']] ,
    ['Muk', 0.45, ['Sky Stairway'], ['Grimer', 38, False, 87], False, ['Late']] ,
    ['Shellder', 0.5589999999999999, ['Surrounded Sea'], [], False, ['Late']] ,
    ['Cloyster', 0.45, ['Miracle Sea'], ['Shellder', 0, True, 89], False, ['Late']] ,
    ['Gastly', 0.577, ['Sky Stairway'], [], False, ['Late']] ,
    ['Haunter', 0.5, ['Sky Stairway'], ['Gastly', 25, False, 91], False, ['Late']] ,
    ['Gengar', 0.395, ['Sky Stairway'], ['Haunter', 0, True, 92], False, ['Late']] ,
    ['Onix', 0.505, ['Mt. Travail'], [], False, ['Late']] ,
    ['Drowzee', 0.5589999999999999, ['Spacial Rift'], [], False, ['Late']] ,
    ['Hypno', 0.45, ['Spacial Rift'], ['Drowzee', 26, False, 95], False, ['Late']] ,
    ['Krabby', 0.5589999999999999, ['Craggy Coast'], [], False, ['Early']] ,
    ['Kingler', 0.45, ['Brine Cave'], ['Krabby', 28, False, 97], False, ['Early']] ,
    ['Voltorb', 0.5589999999999999, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']] ,
    ['Electrode', 0.45, ['Concealed Ruins', 'World Abyss'], ['Voltorb', 30, False, 99], False, ['Late', 'Late']] ,
    ['Exeggcute', 0.5549999999999999, ['Lush Prairie', 'Mystifying Forest', 'Mystery Jungle'], [], False, ['Early', 'Late', 'Late']] ,
    ['Exeggutor', 0.5, ['Apple Woods', 'Happy Outlook'], ['Exeggcute', 0, True, 101], False, ['Early', 'Late']] ,
    ['Cubone', 0.577, ['Northern Desert'], [], False, ['Early']] ,
    ['Marowak', 0.45, ['8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Cubone', 28, False, 103], False, ['Late', 'Late', 'Late', 'Late']] ,
    ['Hitmonlee', 0.395, [], ['Tyrogue', 20, True, 235], False, []] ,
    ['Hitmonchan', 0.375, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Tyrogue', 20, True, 235], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Lickitung', 0.577, ['Marine Resort', 'Lost Wilderness'], [], False, ['Late', 'Late']] ,
    ['Koffing', 0.5589999999999999, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Weezing', 0.375, ['Concealed Ruins', 'World Abyss'], ['Koffing', 35, False, 108], False, ['Late', 'Late']] ,
    ['Rhyhorn', 0.5589999999999999, ['Northern Desert', 'Shimmer Hill'], [], False, ['Early', 'Late']] ,
    ['Rhydon', 0.395, ['Sky Stairway'], ['Rhyhorn', 42, False, 110], False, ['Late']] ,
    ['Chansey', 0.5640000000000001, ['Happy Outlook'], ['Happiny', 0, True, 439], False, ['Late']] ,
    ['Tangela', 0.5589999999999999, ['Waterfall Cave'], [], False, ['Early']] ,
    ['Kangaskhan', 0.5589999999999999, ['Mt. Travail'], [], False, ['Late']] ,
    ['Horsea', 0.577, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Seadra', 0.395, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Horsea', 32, False, 115], False, ['Late', 'Late', 'Late']] ,
    ['Goldeen', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Seaking', 0.45, ['Lake Afar'], ['Goldeen', 33, False, 117], False, ['Late']] ,
    ['Staryu', 0.577, ['Brine Cave'], [], False, ['Early']] ,
    ['Starmie', 0.45, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Staryu', 0, True, 119], False, ['Late', 'Late', 'Late']] ,
    ['Mr. Mime', 0.45, ['Mt. Travail', 'Lost Wilderness'], ['Mime Jr.', 18, True, 438], False, ['Late', 'Late']] ,
    ['Scyther', 0.577, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Jynx', 0.45, ['Crevice Cave', 'Mt. Avalanche'], ['Smoochum', 30, False, 237], False, ['Late', 'Late']] ,
    ['Electabuzz', 0.5, ['Amp Plains'], ['Elekid', 30, False, 238], False, ['Early']] ,
    ['Magmar', 0.5, ['Steam Cave', 'Lost Wilderness'], ['Magby', 30, False, 239], False, ['Early', 'Late']] ,
    ['Pinsir', 0.577, ['Foggy Forest'], [], False, ['Early']] ,
    ['Tauros', 0.5589999999999999, ['Amp Plains', 'Shimmer Hill'], [], False, ['Early', 'Late']] ,
    ['Magikarp', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Gyarados', 0.45, ['Bottomless Sea'], ['Magikarp', 20, False, 128], False, ['Late']] ,
    ['Lapras', 0.562, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Ditto', 0.577, ['Sky Stairway'], [], False, ['Late']] ,
    ['Eevee', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Vaporeon', 0.375, ['Lake Afar'], ['Eevee', 0, True, 132], False, ['Late']] ,
    ['Jolteon', 0.375, ['Spacial Rift'], ['Eevee', 0, True, 132], False, ['Late']] ,
    ['Flareon', 0.375, [], ['Eevee', 0, True, 132], False, []] ,
    ['Porygon', 0.5589999999999999, ['Spacial Rift'], [], False, ['Late']] ,
    ['Omanyte', 0.5589999999999999, ['Brine Cave', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Omastar', 0.45, [], ['Omanyte', 40, False, 137], False, []] ,
    ['Kabuto', 0.5589999999999999, ['Marine Resort', 'Final Maze'], [], False, ['Late', 'Late']] ,
    ['Kabutops', 0.5, ['Marine Resort'], ['Kabuto', 40, False, 139], False, ['Late']] ,
    ['Aerodactyl', 0.577, ['Mt. Horn', 'Mt. Mistral'], [], False, ['Early', 'Late']] ,
    ['Snorlax', 0.375, ['Mystery Jungle'], ['Munchlax', 0, True, 445], False, ['Late']] ,
    ['Articuno', 0.995, ['Articuno'], [], False, ['Late']] ,
    ['Zapdos', 0.595, ['Amp Plains'], [], True, ['Long']] ,
    ['Moltres', 0.7949999999999999, ['Giant Volcano'], [], True, ['Long']] ,
    ['Dratini', 0.577, ['Craggy Coast', 'Marine Resort'], [], False, ['Early', 'Late']] ,
    ['Dragonair', 0.45, ['Brine Cave'], ['Dratini', 30, False, 146], False, ['Early']] ,
    ['Dragonite', 0.395, [], ['Dragonair', 55, False, 147], False, []] ,
    ['Mewtwo', 1.495, ['Sky Stairway'], [], True, ['Long']] ,
    ['Mew', 0.995, ['Mew'], [], False, ['Late']] ,
    ['Chikorita', 0.577, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Bayleef', 0.395, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Chikorita', 16, False, 151], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Meganium', 0.375, ['Mystery Jungle'], ['Bayleef', 32, False, 153], False, ['Late']] ,
    ['Cyndaquil', 0.577, ['Giant Volcano'], [], False, ['Late']] ,
    ['Quilava', 0.395, ['Giant Volcano'], ['Cyndaquil', 14, False, 155], False, ['Late']] ,
    ['Typhlosion', 0.375, [], ['Quilava', 36, False, 156], False, []] ,
    ['Totodile', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Croconaw', 0.395, ['Lake Afar'], ['Totodile', 18, False, 157], False, ['Late']] ,
    ['Feraligatr', 0.375, ['Lake Afar'], ['Croconaw', 30, False, 158], False, ['Late']] ,
    ['Sentret', 0.5589999999999999, ['Mt. Travail', 'Shimmer Hill'], [], False, ['Late', 'Late']] ,
    ['Furret', 0.45, ['6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Sentret', 15, False, 160], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Hoothoot', 0.5589999999999999, ['Foggy Forest'], [], False, ['Early']] ,
    ['Noctowl', 0.395, ['Foggy Forest'], ['Hoothoot', 20, False, 162], False, ['Early']] ,
    ['Ledyba', 0.577, ['Mt. Travail', 'Midnight Forest'], [], False, ['Late', 'Late']] ,
    ['Ledian', 0.45, ['Mt. Travail', 'Midnight Forest'], ['Ledyba', 18, False, 164], False, ['Late', 'Late']] ,
    ['Spinarak', 0.5589999999999999, ['Mt. Bristle', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Ariados', 0.5, ['Mt. Horn'], ['Spinarak', 22, False, 166], False, ['Early']] ,
    ['Crobat', 0.375, ['Ice Aegis Cave'], ['Golbat', 0, True, 41], False, ['Late']] ,
    ['Chinchou', 0.577, ['Miracle Sea'], [], False, ['Late']] ,
    ['Lanturn', 0.45, ['Miracle Sea'], ['Chinchou', 27, False, 169], False, ['Late']] ,
    ['Pichu', 0.546, ['Amp Plains'], [], False, ['Early']] ,
    ['Cleffa', 0.577, ['Marine Resort'], [], False, ['Late']] ,
    ['Igglybuff', 0.577, ['Marine Resort'], [], False, ['Late']] ,
    ['Togepi', 0.5589999999999999, ['Happy Outlook'], [], False, ['Late']] ,
    ['Togetic', 0.375, ['Happy Outlook'], ['Togepi', 0, True, 174], False, ['Late']] ,
    ['Natu', 0.577, ['Mt. Horn'], [], False, ['Early']] ,
    ['Xatu', 0.45, ['Spacial Rift'], ['Natu', 25, False, 176], False, ['Late']] ,
    ['Mareep', 0.577, ['Amp Plains', 'Shimmer Hill', 'Final Maze'], [], False, ['Early', 'Late', 'Late']] ,
    ['Flaaffy', 0.5, ['Amp Plains'], ['Mareep', 15, False, 178], False, ['Early']] ,
    ['Ampharos', 0.45, ['Landslide Cave', 'Amp Plains'], ['Flaaffy', 30, False, 179], False, ['Early', 'Early']] ,
    ['Bellossom', 0.45, ['Marine Resort'], ['Gloom', 0, True, 43], False, ['Late']] ,
    ['Marill', 0.5, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Azurill', 0, True, 297], False, ['Late', 'Late', 'Late']] ,
    ['Azumarill', 0.5, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Marill', 18, False, 182], False, ['Late', 'Late', 'Late']] ,
    ['Sudowoodo', 0.5, ['Shimmer Desert'], [], False, ['Late']] ,
    ['Politoed', 0.375, ['Lake Afar'], ['Poliwhirl', 0, True, 60], False, ['Late']] ,
    ['Hoppip', 0.577, ['Apple Woods', 'Oran Forest'], [], False, ['Early', 'Early']] ,
    ['Skiploom', 0.5, ['Foggy Forest', 'Lush Prairie', 'Tiny Meadow'], ['Hoppip', 18, False, 186], False, ['Early', 'Early', 'Early']] ,
    ['Jumpluff', 0.395, ['Mt. Mistral', 'Sky Stairway'], ['Skiploom', 27, False, 187], False, ['Late', 'Late']] ,
    ['Aipom', 0.5589999999999999, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Sunkern', 0.547, ['Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Sunflora', 0.375, ['Happy Outlook', 'Mystery Jungle'], ['Sunkern', 0, True, 190], False, ['Late', 'Late']] ,
    ['Yanma', 0.577, ['Steam Cave', 'Steam Cave', 'Lush Prairie'], [], False, ['Early', 'Early', 'Early']] ,
    ['Wooper', 0.577, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']] ,
    ['Quagsire', 0.5, ['Lake Afar'], ['Wooper', 20, False, 193], False, ['Late']] ,
    ['Espeon', 0.375, ['Marine Resort', 'Shimmer Hill'], ['Eevee', 0, True, 132], False, ['Late', 'Late']] ,
    ['Umbreon', 0.375, ['Concealed Ruins', 'World Abyss'], ['Eevee', 0, True, 132], False, ['Late', 'Late']] ,
    ['Murkrow', 0.5589999999999999, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']] ,
    ['Slowking', 0.375, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Slowpoke', 0, True, 78], False, ['Late', 'Late', 'Late']] ,
    ['Misdreavus', 0.577, ['Sky Stairway', 'Final Maze'], [], False, ['Late', 'Late']] ,
    ['Unown', 0.577, ['Ice Aegis Cave'], [], False, ['Late']] ,
    ['Wobbuffet', 0.375, ['Marine Resort'], ['Wynaut', 15, False, 359], False, ['Late']] ,
    ['Girafarig', 0.5589999999999999, ['Amp Plains', 'Shimmer Hill'], [], False, ['Early', 'Late']] ,
    ['Pineco', 0.577, ['Mt. Horn'], [], False, ['Early']] ,
    ['Forretress', 0.5, ['Sky Stairway'], ['Pineco', 31, False, 203], False, ['Late']] ,
    ['Dunsparce', 0.5589999999999999, ['Foggy Forest'], [], False, ['Early']] ,
    ['Gligar', 0.577, ['Spacial Rift'], [], False, ['Late']] ,
    ['Steelix', 0.395, ['Sky Stairway'], ['Onix', 0, True, 94], False, ['Late']] ,
    ['Snubbull', 0.5589999999999999, ['Steam Cave', 'Marine Resort'], [], False, ['Early', 'Late']] ,
    ['Granbull', 0.5, ['Steam Cave', 'Landslide Cave'], ['Snubbull', 23, False, 208], False, ['Early', 'Early']] ,
    ['Qwilfish', 0.5640000000000001, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Scizor', 0.375, ['Mt. Travail'], ['Scyther', 0, True, 122], False, ['Late']] ,
    ['Shuckle', 0.577, ['Steam Cave', 'Landslide Cave'], [], False, ['Early', 'Early']] ,
    ['Heracross', 0.5589999999999999, ['Mt. Travail'], [], False, ['Late']] ,
    ['Sneasel', 0.5589999999999999, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Teddiursa', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Ursaring', 0.375, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail', 'Shimmer Hill'], ['Teddiursa', 30, False, 215], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Slugma', 0.577, ['Steam Cave', 'Giant Volcano'], [], False, ['Early', 'Late']] ,
    ['Magcargo', 0.5, [], ['Slugma', 38, False, 217], False, []] ,
    ['Swinub', 0.577, ['Crevice Cave', 'Final Maze'], [], False, ['Late', 'Late']] ,
    ['Piloswine', 0.375, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Swinub', 33, False, 219], False, ['Late', 'Late', 'Late']] ,
    ['Corsola', 0.577, ['Marine Resort'], [], False, ['Late']] ,
    ['Remoraid', 0.577, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Octillery', 0.375, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Remoraid', 25, False, 222], False, ['Late', 'Late', 'Late']] ,
    ['Delibird', 0.577, ['Blizzard Island', 'Crevice Cave'], [], False, ['Late', 'Late']] ,
    ['Mantine', 0.577, ['Miracle Sea'], ['Mantyke', 0, True, 457], False, ['Late']] ,
    ['Skarmory', 0.577, ['Sky Stairway'], [], False, ['Late']] ,
    ['Houndour', 0.577, ['Shimmer Hill', 'Final Maze'], [], False, ['Late', 'Late']] ,
    ['Houndoom', 0.45, ['Treeshroud Forest'], ['Houndour', 24, False, 227], False, ['Early']] ,
    ['Kingdra', 0.375, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Seadra', 0, True, 116], False, ['Late', 'Late', 'Late']] ,
    ['Phanpy', 0.577, ['Amp Plains', 'Marine Resort', 'Final Maze'], [], False, ['Early', 'Late', 'Late']] ,
    ['Donphan', 0.5, ['Crystal Cave'], ['Phanpy', 25, False, 230], False, ['Early']] ,
    ['Porygon2', 0.545, [], ['Porygon', 0, True, 136], False, []] ,
    ['Stantler', 0.5589999999999999, ['Foggy Forest', 'Shimmer Hill'], [], False, ['Early', 'Late']] ,
    ['Smeargle', 0.563, ['Foggy Forest', 'Marine Resort'], [], False, ['Early', 'Late']] ,
    ['Tyrogue', 0.5589999999999999, ['Mt. Travail', 'Marine Resort'], [], False, ['Late', 'Late']] ,
    ['Hitmontop', 0.375, ['Lost Wilderness'], ['Tyrogue', 20, True, 235], False, ['Late']] ,
    ['Smoochum', 0.5589999999999999, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Elekid', 0.577, ['Amp Plains'], [], False, ['Early']] ,
    ['Magby', 0.577, ['Steam Cave', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Miltank', 0.577, ['Marine Resort', 'Shimmer Hill'], [], False, ['Late', 'Late']] ,
    ['Blissey', 0.375, ['Happy Outlook'], ['Chansey', 0, True, 112], False, ['Late']] ,
    ['Raikou', 1.495, ['Southeastern Islands'], [], True, ['Long']] ,
    ['Entei', 1.495, ['Inferno Cave'], [], True, ['Long']] ,
    ['Suicune', 1.495, ['Treacherous Waters'], [], True, ['Long']] ,
    ['Larvitar', 0.577, ['Northern Desert'], [], False, ['Early']] ,
    ['Pupitar', 0.5, ['Quicksand Cave'], ['Larvitar', 30, False, 245], False, ['Early']] ,
    ['Tyranitar', 0.375, ['Quicksand Cave'], ['Pupitar', 55, False, 246], False, ['Early']] ,
    ['Lugia', 0.595, ['Surrounded Sea'], [], True, ['Long']] ,
    ['Ho-Oh', 0.595, ['Mt. Mistral'], [], True, ['Long']] ,
    ['Celebi', 0.6950000000000001, ['Mystifying Forest', 'Celebi'], [], True, ['Long', 'Long']] ,
    ['Treecko', 0.577, ['Mystery Jungle'], [], False, ['Late']] ,
    ['Grovyle', 0.395, ['Mystery Jungle'], ['Treecko', 16, False, 251], False, ['Late']] ,
    ['Sceptile', 0.375, ['Mystery Jungle'], ['Grovyle', 36, False, 252], False, ['Late']] ,
    ['Torchic', 0.577, ['Giant Volcano'], [], False, ['Late']] ,
    ['Combusken', 0.395, ['Giant Volcano'], ['Torchic', 16, False, 254], False, ['Late']] ,
    ['Blaziken', 0.375, [], ['Combusken', 36, False, 255], False, []] ,
    ['Mudkip', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Marshtomp', 0.395, ['Lake Afar'], ['Mudkip', 16, False, 257], False, ['Late']] ,
    ['Swampert', 0.375, ['Lake Afar'], ['Marshtomp', 36, False, 258], False, ['Late']] ,
    ['Poochyena', 0.577, ['Concealed Ruins', 'World Abyss', 'Final Maze'], [], False, ['Late', 'Late', 'Late']] ,
    ['Mightyena', 0.45, ['Concealed Ruins', 'World Abyss'], ['Poochyena', 18, False, 260], False, ['Late', 'Late']] ,
    ['Zigzagoon', 0.577, ['Foggy Forest'], [], False, ['Early']] ,
    ['Linoone', 0.5, ['Shimmer Hill'], ['Zigzagoon', 20, False, 262], False, ['Late']] ,
    ['Wurmple', 0.5589999999999999, ['Oran Forest', 'Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Early', 'Late', 'Late', 'Late']] ,
    ['Silcoon', 0.395, ['Lush Prairie', 'Mystery Jungle'], ['Wurmple', 7, False, 264], False, ['Early', 'Late']] ,
    ['Beautifly', 0.5, ['Mt. Horn', 'Lush Prairie', 'Midnight Forest'], ['Silcoon', 10, False, 265], False, ['Early', 'Early', 'Late']] ,
    ['Cascoon', 0.395, ['Mt. Horn', 'Lush Prairie', 'Mystery Jungle'], ['Wurmple', 7, False, 264], False, ['Early', 'Early', 'Late']] ,
    ['Dustox', 0.5, ['Landslide Cave'], ['Cascoon', 10, False, 267], False, ['Early']] ,
    ['Lotad', 0.5589999999999999, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']] ,
    ['Lombre', 0.45, ['Lake Afar'], ['Lotad', 14, False, 269], False, ['Late']] ,
    ['Ludicolo', 0.375, ['Lake Afar'], ['Lombre', 0, True, 270], False, ['Late']] ,
    ['Seedot', 0.577, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Nuzleaf', 0.5, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], ['Seedot', 14, False, 272], False, ['Late', 'Late', 'Late']] ,
    ['Shiftry', 0.375, ['Lost Wilderness'], ['Nuzleaf', 0, True, 273], False, ['Late']] ,
    ['Taillow', 0.5589999999999999, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']] ,
    ['Swellow', 0.5, ['Concealed Ruins', 'Mt. Mistral', 'World Abyss'], ['Taillow', 22, False, 275], False, ['Late', 'Late', 'Late']] ,
    ['Wingull', 0.5589999999999999, ['Craggy Coast', 'Marine Resort'], [], False, ['Early', 'Late']] ,
    ['Pelipper', 0.375, ['Brine Cave', 'Marine Resort'], ['Wingull', 25, False, 277], False, ['Early', 'Late']] ,
    ['Ralts', 0.545, ['Treeshroud Forest'], [], False, ['Early']] ,
    ['Kirlia', 0.5, ['Treeshroud Forest'], ['Ralts', 20, False, 279], False, ['Early']] ,
    ['Gardevoir', 0.395, [], ['Kirlia', 30, False, 280], False, []] ,
    ['Surskit', 0.5589999999999999, ['Waterfall Cave'], [], False, ['Early']] ,
    ['Masquerain', 0.395, ['Serenity River'], ['Surskit', 22, False, 282], False, ['Early']] ,
    ['Shroomish', 0.5589999999999999, ['Mt. Horn', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Breloom', 0.5, ['Foggy Forest', 'Tiny Meadow'], ['Shroomish', 23, False, 284], False, ['Early', 'Early']] ,
    ['Slakoth', 0.577, ['Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late']] ,
    ['Vigoroth', 0.395, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Slakoth', 18, False, 286], False, ['Late', 'Late', 'Late']] ,
    ['Slaking', 0.375, ['Crevice Cave', 'Mt. Avalanche'], ['Vigoroth', 36, False, 287], False, ['Late', 'Late']] ,
    ['Nincada', 0.5589999999999999, ['Quicksand Cave', 'Midnight Forest'], [], False, ['Early', 'Late']] ,
    ['Ninjask', 0.5, ['Quicksand Cave'], ['Nincada', 20, False, 289], False, ['Early']] ,
    ['Shedinja', 0.375, ['8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Nincada', 20, False, 289], False, ['Late', 'Late', 'Late', 'Late']] ,
    ['Whismur', 0.577, ['Marine Resort'], [], False, ['Late']] ,
    ['Loudred', 0.395, ['Concealed Ruins', 'World Abyss'], ['Whismur', 20, False, 292], False, ['Late', 'Late']] ,
    ['Exploud', 0.375, ['Concealed Ruins', 'World Abyss'], ['Loudred', 40, False, 293], False, ['Late', 'Late']] ,
    ['Makuhita', 0.535, ['Lost Wilderness'], [], False, ['Late']] ,
    ['Hariyama', 0.375, ['Lost Wilderness'], ['Makuhita', 24, False, 295], False, ['Late']] ,
    ['Azurill', 0.577, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Nosepass', 0.5589999999999999, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Skitty', 0.5589999999999999, ['Happy Outlook'], [], False, ['Late']] ,
    ['Delcatty', 0.375, ['Concealed Ruins', 'World Abyss'], ['Skitty', 0, True, 299], False, ['Late', 'Late']] ,
    ['Sableye', 0.577, ['Spacial Rift'], [], False, ['Late']] ,
    ['Mawile', 0.5589999999999999, ['Quicksand Cave', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Aron', 0.5589999999999999, ['Northern Desert'], [], False, ['Early']] ,
    ['Lairon', 0.5, ['Northern Desert'], ['Aron', 32, False, 203], False, ['Early']] ,
    ['Aggron', 0.395, [], ['Lairon', 42, False, 204], False, []] ,
    ['Meditite', 0.55, ['Mt. Travail', 'Lost Wilderness', 'Final Maze'], [], False, ['Late', 'Late', 'Late']] ,
    ['Medicham', 0.375, ['Mt. Travail', 'Lost Wilderness'], ['Meditite', 37, False, 206], False, ['Late', 'Late']] ,
    ['Electrike', 0.5589999999999999, ['Amp Plains'], [], False, ['Early']] ,
    ['Manectric', 0.395, [], ['Electrike', 26, False, 208], False, []] ,
    ['Plusle', 0.577, ['Amp Plains'], [], False, ['Early']] ,
    ['Minun', 0.577, ['Amp Plains'], [], False, ['Early']] ,
    ['Volbeat', 0.577, ['Steam Cave'], [], False, ['Early']] ,
    ['Illumise', 0.577, ['Steam Cave'], [], False, ['Early']] ,
    ['Roselia', 0.5589999999999999, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Midnight Forest', 'Mystery Jungle'], ['Budew', 0, True, 405], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Gulpin', 0.5640000000000001, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Swalot', 0.375, ['Marine Resort'], ['Gulpin', 26, False, 315], False, ['Late']] ,
    ['Carvanha', 0.5, ['Surrounded Sea'], [], False, ['Late']] ,
    ['Sharpedo', 0.375, ['Miracle Sea'], ['Carvanha', 30, False, 317], False, ['Late']] ,
    ['Wailmer', 0.535, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Wailord', 0.375, ['Surrounded Sea', 'Bottomless Sea'], ['Wailmer', 40, False, 319], False, ['Late', 'Late']] ,
    ['Numel', 0.5589999999999999, ['Steam Cave', 'Giant Volcano'], [], False, ['Early', 'Late']] ,
    ['Camerupt', 0.375, ['Shimmer Hill', 'Giant Volcano'], ['Numel', 33, False, 321], False, ['Late', 'Late']] ,
    ['Torkoal', 0.5589999999999999, ['Giant Volcano'], [], False, ['Late']] ,
    ['Spoink', 0.5589999999999999, ['Marine Resort'], [], False, ['Late']] ,
    ['Grumpig', 0.395, [], ['Spoink', 32, False, 324], False, []] ,
    ['Spinda', 0.5589999999999999, ['Marine Resort', 'Lost Wilderness'], [], False, ['Late', 'Late']] ,
    ['Trapinch', 0.577, ['Northern Desert'], [], False, ['Early']] ,
    ['Vibrava', 0.5, ['Quicksand Cave'], ['Trapinch', 35, False, 327], False, ['Early']] ,
    ['Flygon', 0.375, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mt. Mistral', 'Mystery Jungle'], ['Vibrava', 45, False, 328], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Cacnea', 0.5589999999999999, ['Northern Desert'], [], False, ['Early']] ,
    ['Cacturne', 0.5, ['Northern Desert', 'Happy Outlook'], ['Cacnea', 32, False, 330], False, ['Early', 'Late']] ,
    ['Swablu', 0.5589999999999999, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Altaria', 0.375, ['Crevice Cave', 'Mt. Avalanche'], ['Swablu', 35, False, 332], False, ['Late', 'Late']] ,
    ['Zangoose', 0.5589999999999999, ['Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late']] ,
    ['Seviper', 0.5589999999999999, ['Crystal Cave'], [], False, ['Early']] ,
    ['Lunatone', 0.5589999999999999, ['Spacial Rift'], [], False, ['Late']] ,
    ['Solrock', 0.5589999999999999, ['Spacial Rift'], [], False, ['Late']] ,
    ['Barboach', 0.577, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']] ,
    ['Whiscash', 0.5, ['Waterfall Cave'], ['Barboach', 30, False, 338], False, ['Early']] ,
    ['Corphish', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Crawdaunt', 0.375, ['Lake Afar'], ['Corphish', 30, False, 340], False, ['Late']] ,
    ['Baltoy', 0.551, ['Northern Desert'], [], False, ['Early']] ,
    ['Claydol', 0.5, ['Sky Stairway'], ['Baltoy', 36, False, 342], False, ['Late']] ,
    ['Lileep', 0.5589999999999999, ['Drenched Bluff'], [], False, ['Early']] ,
    ['Cradily', 0.45, ['Miracle Sea'], ['Lileep', 40, False, 344], False, ['Late']] ,
    ['Anorith', 0.577, ['Drenched Bluff'], [], False, ['Early']] ,
    ['Armaldo', 0.45, ['Mt. Avalanche'], ['Anorith', 40, False, 346], False, ['Late']] ,
    ['Feebas', 0.577, ['Lake Afar'], [], False, ['Late']] ,
    ['Milotic', 0.375, ['Lake Afar'], ['Feebas', 0, True, 348], False, ['Late']] ,
    ['Castform', 0.5589999999999999, ['Blizzard Island', 'Shimmer Hill'], [], False, ['Late', 'Late']] ,
    ['Kecleon', 0.0, ['Waterfall Cave', 'Apple Woods', 'Craggy Coast', 'Mt. Horn', 'Amp Plains', 'Crystal Cave', 'Crystal Crossing', 'Treeshroud Forest', 'Tiny Meadow', 'Lush Prairie', 'Serenity River', 'Landslide Cave', 'Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail', 'Concealed Ruins', 'Marine Resort', 'Lake Afar', 'Happy Outlook', 'Mt. Mistral', 'Shimmer Hill', 'Lost Wilderness', 'Midnight Forest', 'Star Cave', 'Mystery Jungle'], [], True, ['Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long', 'Long']] ,
    ['Shuppet', 0.5589999999999999, ['Concealed Ruins'], [], False, ['Late']] ,
    ['Banette', 0.395, ['Sky Stairway'], ['Shuppet', 37, False, 352], False, ['Late']] ,
    ['Duskull', 0.5589999999999999, ['Sky Stairway'], [], False, ['Late']] ,
    ['Dusclops', 0.395, [], ['Duskull', 37, False, 354], False, []] ,
    ['Tropius', 0.5589999999999999, ['Spacial Rift'], [], False, ['Late']] ,
    ['Chimecho', 0.5640000000000001, ['Spacial Rift'], ['Chingling', 0, True, 432], False, ['Late']] ,
    ['Absol', 0.563, ['Crystal Crossing'], [], False, ['Early']] ,
    ['Wynaut', 0.577, ['Marine Resort'], [], False, ['Late']] ,
    ['Snorunt', 0.5589999999999999, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Glalie', 0.5, ['Crystal Crossing'], ['Snorunt', 42, False, 360], False, ['Early']] ,
    ['Spheal', 0.577, ['Craggy Coast'], [], False, ['Early']] ,
    ['Sealeo', 0.5, ['Craggy Coast'], ['Spheal', 32, False, 362], False, ['Early']] ,
    ['Walrein', 0.5, ['Brine Cave'], ['Sealeo', 44, False, 363], False, ['Early']] ,
    ['Clamperl', 0.577, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Huntail', 0.375, ['Miracle Sea'], ['Clamperl', 0, True, 365], False, ['Late']] ,
    ['Gorebyss', 0.375, ['Miracle Sea'], ['Clamperl', 0, True, 365], False, ['Late']] ,
    ['Relicanth', 0.5589999999999999, ['Miracle Sea'], [], False, ['Late']] ,
    ['Luvdisc', 0.577, ['Miracle Sea'], [], False, ['Late']] ,
    ['Bagon', 0.5589999999999999, ['Crystal Crossing', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Shelgon', 0.5, ['Sky Stairway'], ['Bagon', 30, False, 370], False, ['Late']] ,
    ['Salamence', 0.395, [], ['Shelgon', 50, False, 371], False, []] ,
    ['Beldum', 0.5589999999999999, ['Crystal Cave'], [], False, ['Early']] ,
    ['Metang', 0.5, ['Sky Stairway'], ['Beldum', 20, False, 373], False, ['Late']] ,
    ['Metagross', 0.395, [], ['Metang', 45, False, 374], False, []] ,
    ['Regirock', 0.995, ['Regirock'], [], False, ['Late']] ,
    ['Regice', 0.995, ['Regice'], [], False, ['Late']] ,
    ['Registeel', 0.995, ['Registeel'], [], False, ['Late']] ,
    ['Latias', 0.496, ['Spacial Rift', 'Happy Outlook'], [], True, ['Long', 'Long']] ,
    ['Latios', 0.496, ['Spacial Rift', 'Midnight Forest'], [], True, ['Long', 'Long']] ,
    ['Kyogre', 0.995, ['Kyogre'], [], False, ['Late']] ,
    ['Groudon', 0.995, ['Groudon'], [], False, ['Late']] ,
    ['Rayquaza', 0.995, ['Rayquaza'], [], False, ['Late']] ,
    ['Jirachi', 1.495, ['Star Cave'], [], True, ['Long']] ,
    ['Deoxys', 0.395, ['Shimmer Hill'], [], True, ['Long']] ,
    ['Turtwig', 0.577, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']] ,
    ['Grotle', 0.395, ['Mystifying Forest', 'Mystery Jungle'], ['Turtwig', 18, False, 386], False, ['Late', 'Late']] ,
    ['Torterra', 0.375, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Grotle', 32, False, 387], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Chimchar', 0.577, ['Giant Volcano'], [], False, ['Late']] ,
    ['Monferno', 0.395, ['Giant Volcano'], ['Chimchar', 14, False, 389], False, ['Late']] ,
    ['Infernape', 0.375, [], ['Monferno', 36, False, 390], False, []] ,
    ['Piplup', 0.577, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']] ,
    ['Prinplup', 0.395, ['Crevice Cave', 'Mt. Avalanche'], ['Piplup', 16, False, 392], False, ['Late', 'Late']] ,
    ['Empoleon', 0.375, ['Crevice Cave', 'Mt. Avalanche'], ['Prinplup', 36, False, 393], False, ['Late', 'Late']] ,
    ['Starly', 0.577, ['Mt. Bristle', 'Oran Forest'], [], False, ['Early', 'Early']] ,
    ['Staravia', 0.577, ['Tiny Meadow', 'Final Maze'], ['Starly', 14, False, 395], False, ['Early', 'Late']] ,
    ['Staraptor', 0.51, ['Mt. Mistral'], ['Staravia', 34, False, 396], False, ['Late']] ,
    ['Bidoof', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Bibarel', 0.53, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Mt. Travail'], ['Bidoof', 15, False, 398], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Kricketot', 0.577, ['Mystifying Forest'], [], False, ['Late']] ,
    ['Kricketune', 0.54, ['Steam Cave', 'Steam Cave'], ['Kricketot', 10, False, 400], False, ['Early', 'Early']] ,
    ['Shinx', 0.577, ['Amp Plains'], [], False, ['Early']] ,
    ['Luxio', 0.5, ['Amp Plains'], ['Shinx', 15, False, 402], False, ['Early']] ,
    ['Luxray', 0.375, ['Amp Plains'], ['Luxio', 30, False, 403], False, ['Early']] ,
    ['Budew', 0.577, ['Apple Woods', 'Oran Forest', 'Happy Outlook'], [], False, ['Early', 'Early', 'Late']] ,
    ['Roserade', 0.375, ['Mystery Jungle'], ['Roselia', 0, True, 314], False, ['Late']] ,
    ['Cranidos', 0.577, ['Crystal Cave'], [], False, ['Early']] ,
    ['Rampardos', 0.51, [], ['Cranidos', 30, False, 407], False, []] ,
    ['Shieldon', 0.577, ['Crystal Cave'], [], False, ['Early']] ,
    ['Bastiodon', 0.51, [], ['Shieldon', 30, False, 409], False, []] ,
    ['Burmy', 0.577, ['Apple Woods', 'Lush Prairie', 'Oran Forest'], [], False, ['Early', 'Early', 'Early']] ,
    ['Wormadam', 0.577, ['Crystal Cave', 'Crystal Crossing', 'Landslide Cave'], ['Burmy', 20, False, 411], False, ['Early', 'Early', 'Early']] ,
    ['Mothim', 0.577, ['Mt. Mistral', 'Sky Stairway'], ['Burmy', 20, False, 411], False, ['Late', 'Late']] ,
    ['Combee', 0.5589999999999999, ['Apple Woods'], [], False, ['Early']] ,
    ['Vespiquen', 0.45, ['Treeshroud Forest'], ['Combee', 21, True, 414], False, ['Early']] ,
    ['Pachirisu', 0.577, ['Foggy Forest'], [], False, ['Early']] ,
    ['Buizel', 0.577, ['Marine Resort'], [], False, ['Late']] ,
    ['Floatzel', 0.5, ['Crystal Crossing'], ['Buizel', 26, False, 417], False, ['Early']] ,
    ['Cherubi', 0.577, ['Foggy Forest'], [], False, ['Early']] ,
    ['Cherrim', 0.51, ['Treeshroud Forest'], ['Cherubi', 25, False, 419], False, ['Early']] ,
    ['Shellos', 0.5589999999999999, ['Drenched Bluff', 'Miracle Sea'], [], False, ['Early', 'Late']] ,
    ['Gastrodon', 0.577, ['Craggy Coast', 'Brine Cave'], ['Shellos', 30, False, 421], False, ['Early', 'Early']] ,
    ['Ambipom', 0.577, ['Marine Resort', 'Sky Stairway'], [], False, ['Late', 'Late']] ,
    ['Drifloon', 0.52, ['Sky Stairway'], [], False, ['Late']] ,
    ['Drifblim', 0.52, ['Mt. Mistral'], ['Drifloon', 28, False, 424], False, ['Late']] ,
    ['Buneary', 0.577, ['Foggy Forest'], [], False, ['Early']] ,
    ['Lopunny', 0.375, ['Mystery Jungle'], ['Buneary', 0, True, 326], False, ['Late']] ,
    ['Mismagius', 0.577, ['Mt. Mistral'], ['Misdreavus', 0, True, 199], False, ['Late']] ,
    ['Honchkrow', 0.375, ['Spacial Rift'], ['Murkrow', 0, True, 197], False, ['Late']] ,
    ['Glameow', 0.577, ['Crystal Crossing'], [], False, ['Early']] ,
    ['Purugly', 0.395, [], ['Glameow', 38, False, 430], False, []] ,
    ['Chingling', 0.577, ['Drenched Bluff'], [], False, ['Early']] ,
    ['Stunky', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Skuntank', 0.5, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', 'Shimmer Hill', 'Mystery Jungle'], ['Stunky', 34, False, 433], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']] ,
    ['Bronzor', 0.577, ['Spacial Rift'], [], False, ['Late']] ,
    ['Bronzong', 0.51, [], ['Bronzor', 33, False, 336], False, []] ,
    ['Bonsly', 0.577, ['Mt. Horn'], [], False, ['Early']] ,
    ['Mime Jr.', 0.577, ['Happy Outlook'], [], False, ['Late']] ,
    ['Happiny', 0.577, ['Happy Outlook'], [], False, ['Late']] ,
    ['Chatot', 0.395, ['Spacial Rift'], [], False, ['Late']] ,
    ['Spiritomb', 0.395, ['Spacial Rift', 'Sky Stairway'], [], False, ['Late', 'Late']] ,
    ['Gible', 0.577, ['Landslide Cave'], [], False, ['Early']] ,
    ['Gabite', 0.577, ['Sky Stairway'], ['Gible', 24, False, 442], False, ['Late']] ,
    ['Garchomp', 0.5, ['Shimmer Desert'], ['Gabite', 48, False, 443], False, ['Late']] ,
    ['Munchlax', 0.577, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']] ,
    ['Riolu', 0.577, ['Crystal Cave'], [], False, ['Early']] ,
    ['Lucario', 0.395, ['Lost Wilderness'], ['Riolu', 0, True, 446], False, ['Late']] ,
    ['Hippopotas', 0.577, ['Quicksand Cave'], [], False, ['Early']] ,
    ['Hippowdon', 0.577, [], ['Hippopotas', 34, False, 448], False, []] ,
    ['Skorupi', 0.577, ['Quicksand Cave', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Drapion', 0.375, ['Spacial Rift'], ['Skorupi', 40, False, 450], False, ['Late']] ,
    ['Croagunk', 0.577, ['Marine Resort', 'Lost Wilderness'], [], False, ['Late', 'Late']] ,
    ['Toxicroak', 0.375, ['Spacial Rift'], ['Croagunk', 37, False, 452], False, ['Late']] ,
    ['Carnivine', 0.577, ['Northern Desert', 'Final Maze'], [], False, ['Early', 'Late']] ,
    ['Finneon', 0.577, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']] ,
    ['Lumineon', 0.577, ['Miracle Sea'], ['Finneon', 31, False, 455], False, ['Late']] ,
    ['Mantyke', 0.577, ['Miracle Sea'], [], False, ['Late']] ,
    ['Snover', 0.577, ['Crevice Cave'], [], False, ['Late']] ,
    ['Abomasnow', 0.395, [], ['Snover', 40, False, 458], False, []] ,
    ['Weavile', 0.375, ['Crevice Cave', 'Mt. Avalanche'], ['Sneasel', 0, True, 214], False, ['Late', 'Late']] ,
    ['Magnezone', 0.375, ['Spacial Rift'], ['Magneton', 0, True, 81], False, ['Late']] ,
    ['Lickilicky', 0.375, ['Marine Resort'], ['Lickitung', 33, True, 107], False, ['Late']] ,
    ['Rhyperior', 0.375, ['Shimmer Desert'], ['Rhydon', 0, True, 111], False, ['Late']] ,
    ['Tangrowth', 0.577, ['Sky Stairway'], ['Tangela', 33, True, 113], False, ['Late']] ,
    ['Electivire', 0.375, ['Spacial Rift'], ['Electabuzz', 0, True, 124], False, ['Late']] ,
    ['Magmortar', 0.395, [], ['Magmar', 0, True, 125], False, []] ,
    ['Togekiss', 0.375, ['Sky Stairway'], ['Togetic', 0, True, 175], False, ['Late']] ,
    ['Yanmega', 0.45, ['Amp Plains'], ['Yanma', 33, True, 192], False, ['Early']] ,
    ['Leafeon', 0.395, ['Sky Stairway'], ['Eevee', 0, True, 132], False, ['Late']] ,
    ['Glaceon', 0.395, ['Crevice Cave'], ['Eevee', 0, True, 132], False, ['Late']] ,
    ['Gliscor', 0.45, ['Mt. Mistral', 'Sky Stairway'], ['Gligar', 0, True, 206], False, ['Late', 'Late']] ,
    ['Mamoswine', 0.375, ['Crevice Cave', 'Mt. Avalanche'], ['Piloswine', 1, True, 220], False, ['Late', 'Late']] ,
    ['Porygon-Z', 0.45, [], ['Porygon2', 0, True, 232], False, []] ,
    ['Gallade', 0.375, ['Spacial Rift'], ['Kirlia', 0, True, 280], False, ['Late']] ,
    ['Probopass', 0.577, ['Sky Stairway'], ['Nosepass', 0, True, 298], False, ['Late']] ,
    ['Dusknoir', 0.375, ['Spacial Rift', 'Sky Stairway'], ['Dusclops', 0, True, 355], False, ['Late', 'Late']] ,
    ['Froslass', 0.395, ['Crystal Crossing'], ['Snorunt', 0, True, 360], False, ['Early']] ,
    ['Rotom', 0.375, ['Midnight Forest'], [], False, ['Late']] ,
    ['Uxie', 1.495, ['Uxie'], [], False, ['Late']] ,
    ['Mesprit', 1.495, ['Mesprit'], [], False, ['Late']] ,
    ['Azelf', 1.495, ['Azelf'], [], False, ['Late']] ,
    ['Dialga', 1.495, ['Dialga', 'Primal Dialga'], [], False, ['Late', 'Late']] ,
    ['Palkia', 1.495, ['Palkia'], [], False, ['Late']] ,
    ['Heatran', 0.995, ['Heatran'], [], False, ['Late']] ,
    ['Regigigas', 1.495, ['Regigigas'], [], False, ['Late']] ,
    ['Giratina', 0.995, ['Giratina'], [], False, ['Late']] ,
    ['Cresselia', 1.495, ['Cresselia'], [], False, ['Late']] ,
    ['Phione', 1.495, ['Phione'], [], False, ['Late']] ,
    ['Manaphy', 1.495, ['Manaphy'], [], False, ['Late']] ,
    ['Darkrai', 0.275, ['Mystifying Forest', 'Crevice Cave', 'Miracle Sea', 'Mt. Travail', 'Spacial Rift'], [], True, ['Long', 'Long', 'Long', 'Long', 'Long']] ,
    ['Shaymin', 1.495, ['Shaymin'], [], False, ['Late']]
]

dungeon_location = {
    "Beach Cave" : "Early",
    "Drenched Bluff" : "Early",
    "Mt. Bristle" : "Early",
    "Waterfall Cave" : "Early",
    "Apple Woods" : "Early",
    "Craggy Coast" : "Early",
    "Mt. Horn" : "Early",
    "Foggy Forest" : "Early",
    "Steam Cave" : "Early",
    "Amp Plains" : "Early",
    "Northern Desert" : "Early",
    "Quicksand Cave" : "Early",
    "Crystal Cave" : "Early",
    "Crystal Crossing" : "Early",
    "Chasm Cave" : "Early",
    "Dark Hill" : "Early",
    "Sealed Ruin" : "Early",
    "Dusk Forest" : "Early",
    "Deep Dusk Forest" : "Early",
    "Treeshroud Forest" : "Early",
    "Brine Cave" : "Early",
    "Hidden Land" : "Late",
    "Temporal Tower" : "Late",
    "Mystifying Forest" : "Late",
    "1st Station Pass" : "Late",
    "2nd Station Pass" : "Late",
    "3rd Station Pass" : "Late",
    "4th Station Pass" : "Late",
    "5th Station Pass" : "Late",
    "6th Station Pass" : "Late",
    "7th Station Pass" : "Late",
    "8th Station Pass" : "Late",
    "9th Station Pass" : "Late",
    "Sky Peak Summit Pass" : "Late",
    "Blizzard Island" : "Late",
    "Crevice Cave" : "Late",
    "Surrounded Sea" : "Late",
    "Miracle Sea" : "Late",
    "Ice Aegis Cave" : "Late",
    "Mt. Travail" : "Late",
    "The Nightmare" : "Late",
    "Spacial Rift" : "Late",
    "Side Path" : "Early",
    "Rock Path" : "Early",
    "Forest Path" : "Early",
    "Oran Forest" : "Early",
    "Tiny Meadow" : "Early",
    "Lush Prairie" : "Early",
    "Labyrinth Cave" : "Early",
    "Serenity River" : "Early",
    "Landslide Cave" : "Early",
    "Lake Afar" : "Late",
    "Happy Outlook" : "Late",
    "Mt. Mistral" : "Late",
    "Shimmer Hill" : "Late",
    "Lost Wilderness" : "Late",
    "Midnight Forest" : "Late",
    "Bottomless Sea" : "Late",
    "Shimmer Desert" : "Late",
    "Mt. Avalanche" : "Late",
    "Giant Volcano" : "Late",
    "World Abyss" : "Late",
    "Sky Stairway" : "Late",
    "Star Cave" : "Late",
    "Mystery Jungle" : "Late",
    "Concealed Ruins" : "Late",
    "Marine Resort" : "Late",
    "Zero Isle North" : "Long",
    "Zero Isle East" : "Long",
    "Zero Isle West" : "Long",
    "Zero Isle South" : "Long",
    "Zero Isle Center" : "Long",
    "Final Maze" : "Long",
    "Destiny Tower" : "Long",
    "Oblivion Forest" : "Long",
    "Treacherous Waters" : "Long",
    "Southeastern Islands" : "Long",
    "Inferno Cave" : "Long",
    "Lush Prairie" : "Early",
    "Articuno" : "Late",
    "Mew" : "Late",
    "Celebi" : "Late",
    "Regirock" : "Late",
    "Regice" : "Late",
    "Registeel" : "Late",
    "Kyogre" : "Late",
    "Groudon" : "Late",
    "Rayquaza" : "Late",
    "Uxie" : "Late",
    "Azelf" : "Late",
    "Mesprit" : "Late",
    "Dialga" : "Late",
    "Palkia" : "Late",
    "Heatran" : "Late",
    "Cresselia" : "Late",
    "Regigigas" : "Late",
    "Giratina" : "Late",
    "Phione" : "Late",
    "Manaphy" : "Late",
    "Shaymin" : "Late",
    "" : ""
}