#list of pokemon with data about the recruitment
# [pokemon_name, recruit rate, [Location], [pre_evolution, level_requirement, item_requirement], long_location, Dungeon Location]

pokemon_info =  [
    ['Bulbasaur', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']],
    ['Ivysaur', -0.1, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Bulbasaur', 16, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Venusaur', -0.12, ['Mystery Jungle'], ['Ivysaur', 32, False], False, ['Late']], 
    ['Charmander', 0.08, ['Giant Volcano'], [], False, ['Late']], 
    ['Charmeleon', -0.1, ['Giant Volcano'], ['Charmander', 16, False], False, ['Late']], 
    ['Charizard', -0.12, ['Spacial Rift'], ['Charmeleon', 36, False], False, ['Late']], 
    ['Squirtle', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Wartortle', -0.1, ['Lake Afar'], ['Squirtle', 16, False], False, ['Late']], 
    ['Blastoise', -0.12, ['Lake Afar'], ['Wartortle', 36, False], False, ['Late']], 
    ['Caterpie', 0.08, ['Apple Woods', 'Oran Forest'], [], False, ['Early', 'Early']], 
    ['Metapod', -0.1, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', 'Happy Outlook', 'Mystery Jungle'], ['Caterpie', 7, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Butterfree', 0.06, ['Apple Woods'], ['Metapod', 10, False], False, ['Early']], 
    ['Weedle', 0.08, ['Apple Woods'], [], False, ['Early']], 
    ['Kakuna', 0.05, ['Apple Woods'], ['Weedle', 7, False], False, ['Early']], 
    ['Beedrill', 0.05, ['Apple Woods', 'Midnight Forest'], ['Kakuna', 10, False], False, ['Early', 'Late']], 
    ['Pidgey', 0.08, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']], 
    ['Pidgeotto', -0.05, ['Concealed Ruins', 'World Abyss'], ['Pidgey', 18, False], False, ['Late', 'Late']], 
    ['Pidgeot', -0.1, ['Concealed Ruins', 'Mt. Mistral', 'World Abyss'], ['Pidgeotto', 36, False], False, ['Late', 'Late', 'Late']], 
    ['Rattata', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Raticate', -0.05, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Midnight Forest', 'Mystery Jungle'], ['Rattata', 20, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Spearow', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Fearow', -0.05, ['5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail', 'Mt. Mistral'], ['Spearow', 20, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Ekans', 0.01, ['Shimmer Desert'], [], False, ['Late']], 
    ['Arbok', -0.12, ['Shimmer Desert'], ['Ekans', 22, False], False, ['Late']], 
    ['Pikachu', 0.08, ['Amp Plains'], ['Pichu', True], False, ['Early']], 
    ['Raichu', -0.12, ['Sky Stairway'], ['Pikachu', True], False, ['Late']], 
    ['Sandshrew', 0.08, ['Northern Desert', 'Shimmer Desert'], [], False, ['Early', 'Late']], 
    ['Sandslash', 0.01, ['Northern Desert', 'Quicksand Cave', 'Shimmer Desert'], ['Sandshrew', 22, False], False, ['Early', 'Early', 'Late']], 
    ['Nidoran-F', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Nidorina', 0.01, ['Mt. Bristle', 'Labyrinth Cave'], ['Nidoran-F', 16, False], False, ['Early', 'Early']], 
    ['Nidoqueen', -0.12, ['Concealed Ruins', 'World Abyss'], ['Nidorina', True], False, ['Late', 'Late']], 
    ['Nidoran-M', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Nidorino', 0.01, ['Mt. Bristle', 'Labyrinth Cave'], ['Nidoran-M', 16, False], False, ['Early', 'Early']], 
    ['Nidoking', -0.12, ['Shimmer Desert'], ['Nidorino', True], False, ['Late']], 
    ['Clefairy', -0.05, ['Marine Resort'], [], False, ['Late']], 
    ['Clefable', -0.12, ['Marine Resort'], ['Clefairy', True], False, ['Late']], 
    ['Vulpix', 0.08, ['Sky Stairway'], [], False, ['Late']], 
    ['Ninetales', -0.05, ['Treeshroud Forest'], ['Vulpix', True], False, ['Early']], 
    ['Jigglypuff', -0.05, ['Marine Resort'], ['Igglybuff', True], False, ['Late']], 
    ['Wigglytuff', -0.12, ['Marine Resort'], ['Jigglypuff', True], False, ['Late']], 
    ['Zubat', 0.06, ['Aegis Cave'], [], False, ['Late']], 
    ['Golbat', -0.05, ['Aegis Cave', 'Labyrinth Cave'], ['Zubat', 22, False], False, ['Late', 'Early']], 
    ['Oddish', 0.08, ['Apple Woods', 'Oran Forest', 'Happy Outlook'], [], False, ['Early', 'Early', 'Late']], 
    ['Gloom', 0.0, ['Apple Woods'], ['Oddish', 21, False], False, ['Early']], 
    ['Vileplume', -0.12, ['Mystery Jungle'], ['Gloom', True], False, ['Late']], 
    ['Paras', 0.08, ['Apple Woods'], [], False, ['Early']], 
    ['Parasect', -0.05, ['Mt. Horn'], ['Paras', 24, False], False, ['Early']], 
    ['Venonat', 0.08, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Venomoth', -0.05, ['Mt. Horn', 'Landslide Cave', 'Mt. Mistral', 'Midnight Forest'], ['Venonat', 31, False], False, ['Early', 'Early', 'Late', 'Late']], 
    ['Diglett', 0.08, ['Shimmer Desert'], [], False, ['Late']], 
    ['Dugtrio', -0.05, ['Shimmer Desert'], ['Diglett', 26, False], False, ['Late']], 
    ['Meowth', 0.08, ['Happy Outlook'], [], False, ['Late']], 
    ['Persian', -0.12, ['Happy Outlook'], ['Meowth', 28, False], False, ['Late']], 
    ['Psyduck', 0.08, ['Waterfall Cave'], [], False, ['Early']],
    ['Golduck', -0.12, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Psyduck', 33, False], False, ['Late', 'Late', 'Late']], 
    ['Mankey', 0.08, ['Mt. Travail'], [], False, ['Late']], 
    ['Primeape', -0.05, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Mankey', 28, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Growlithe', 0.08, ['Giant Volcano'], [], False, ['Late']], 
    ['Arcanine', -0.12, [''], ['Growlithe', True], False, ['']], 
    ['Poliwag', 0.06, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']], 
    ['Poliwhirl', 0.01, ['Lake Afar'], ['Poliwag', 25, False], False, ['Late']], 
    ['Poliwrath', 0.01, ['Lake Afar'], ['Poliwhirl', True], False, ['Late']], 
    ['Abra', 0.08, ['Lost Wilderness'], [], False, ['Late']], 
    ['Kadabra', -0.05, ['Treeshroud Forest', 'Spacial Rift', 'Lost Wilderness'], ['Abra', 16, False], False, ['Early', 'Late', 'Late']], 
    ['Alakazam', -0.12, ['Treeshroud Forest'], ['Kadabra', True], False, ['Early']], 
    ['Machop', 0.08, ['Mt. Bristle', 'Labyrinth Cave', 'Final Maze'], [], False, ['Early', 'Early', 'Late']], 
    ['Machoke', -0.05, ['Aegis Cave'], ['Machop', 28, False], False, ['Late']], 
    ['Machamp', -0.1, ['Aegis Cave'], ['Machoke', True], False, ['Late']], 
    ['Bellsprout', 0.08, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Weepinbell', -0.1, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Bellsprout', 21, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Victreebel', -0.12, ['Mystery Jungle'], ['Weepinbell', True], False, ['Late']], 
    ['Tentacool', 0.08, ['Brine Cave'], [], False, ['Early']], 
    ['Tentacruel', -0.05, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Tentacool', 30, False], False, ['Late', 'Late', 'Late']], 
    ['Geodude', 0.08, ['Mt. Bristle'], [], False, ['Early']], 
    ['Graveler', 0.01, ['Crystal Cave'], ['Geodude', 25, False], False, ['Early']], 
    ['Golem', 0.01, ['Crystal Cave'], ['Graveler', True], False, ['Early']], 
    ['Ponyta', 0.08, ['Giant Volcano'], [], False, ['Late']], 
    ['Rapidash', -0.05, ['Giant Volcano'], ['Ponyta', 40, False], False, ['Late']], 
    ['Slowpoke', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Slowbro', -0.12, ['Surrounded Sea', 'Miracle Sea', 'Marine Resort', 'Bottomless Sea'], ['Slowpoke', 37, False], False, ['Late', 'Late', 'Late', 'Late']], 
    ['Magnemite', 0.08, ['Sky Stairway', 'Final Maze'], [], False, ['Late', 'Late']], 
    ['Magneton', -0.05, ['Sky Stairway'], ['Magnemite', 30, False], False, ['Late']], 
    ['Farfetchd', 0.06, ['Steam Cave', 'Steam Cave'], [], False, ['Early', 'Early']], 
    ['Doduo', 0.06, ['Mt. Bristle', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Dodrio', 0.01, ['Amp Plains'], ['Doduo', 31, False], False, ['Early']], 
    ['Seel', 0.04, ['Brine Cave'], [], False, ['Early']], 
    ['Dewgong', -0.05, ['Brine Cave'], ['Seel', 34, False], False, ['Early']], 
    ['Grimer', 0.06, ['Waterfall Cave'], [], False, ['Early']], 
    ['Muk', -0.05, ['Sky Stairway'], ['Grimer', 38, False], False, ['Late']], 
    ['Shellder', 0.06, ['Surrounded Sea'], [], False, ['Late']], 
    ['Cloyster', -0.05, ['Miracle Sea'], ['Shellder', True], False, ['Late']], 
    ['Gastly', 0.08, ['Sky Stairway'], [], False, ['Late']], 
    ['Haunter', 0.01, ['Sky Stairway'], ['Gastly', 25, False], False, ['Late']], 
    ['Gengar', -0.1, ['Sky Stairway'], ['Haunter', True], False, ['Late']], 
    ['Onix', 0.01, ['Mt. Travail'], [], False, ['Late']], 
    ['Drowzee', 0.06, ['Spacial Rift'], [], False, ['Late']],
    ['Hypno', -0.05, ['Spacial Rift'], ['Drowzee', 26, False], False, ['Late']], 
    ['Krabby', 0.06, ['Craggy Coast'], [], False, ['Early']], 
    ['Kingler', -0.05, ['Brine Cave'], ['Krabby', 28, False], False, ['Early']], 
    ['Voltorb', 0.06, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']], 
    ['Electrode', -0.05, ['Concealed Ruins', 'World Abyss'], ['Voltorb', 30, False], False, ['Late', 'Late']], 
    ['Exeggcute', 0.06, ['Lust Prairie', 'Mystifying Forest', 'Mystery Jungle'], [], False, ['Early', 'Late', 'Late']], 
    ['Exeggutor', 0.01, ['Apple Woods', 'Happy Outlook'], ['Exeggcute', True], False, ['Early', 'Late']], 
    ['Cubone', 0.08, ['Northern Desert'], [], False, ['Early']], 
    ['Marowak', -0.05, ['8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Cubone', 28, False], False, ['Late', 'Late', 'Late', 'Late']], 
    ['Hitmonlee', -0.1, [], ['Tyrogue', 20, True], False, []], 
    ['Hitmonchan', -0.12, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Tyrogue', 20, True], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Lickitung', 0.08, ['Marine Resort', 'Lost Wilderness'], [], False, ['Late', 'Late']], 
    ['Koffing', 0.06, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Weezing', -0.12, ['Concealed Ruins', 'World Abyss'], ['Koffing', 35, False], False, ['Late', 'Late']], 
    ['Rhyhorn', 0.06, ['Northern Desert', 'Shimmer Hill'], [], False, ['Early', 'Late']], 
    ['Rhydon', -0.1, ['Sky Stairway'], ['Rhyhorn', 42, False], False, ['Late']], 
    ['Chansey', 0.07, ['Happy Outlook'], ['Happiny', True], False, ['Late']], 
    ['Tangela', 0.06, ['Waterfall Cave'], [], False, ['Early']], 
    ['Kangaskhan', 0.06, ['Mt. Travail'], [], False, ['Late']], 
    ['Horsea', 0.08, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Seadra', -0.1, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Horsea', 32, False], False, ['Late', 'Late', 'Late']], 
    ['Goldeen', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Seaking', -0.05, ['Lake Afar'], ['Goldeen', 33, False], False, ['Late']], 
    ['Staryu', 0.08, ['Brine Cave'], [], False, ['Early']], 
    ['Starmie', -0.05, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Staryu', True], False, ['Late', 'Late', 'Late']], 
    ['Mr. Mime', -0.05, ['Mt. Travail', 'Lost Wilderness'], ['Mime Jr.', 18, True], False, ['Late', 'Late']], 
    ['Scyther', 0.08, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Jynx', -0.05, ['Crevice Cave', 'Mt. Avalanche'], ['Smoochum', 30, False], False, ['Late', 'Late']], 
    ['Electabuzz', 0.01, ['Amp Plains'], ['Elekid', 30, False], False, ['Early']], 
    ['Magmar', 0.01, ['Steam Cave', 'Lost Wilderness'], ['Magby', 30, False], False, ['Early', 'Late']], 
    ['Pinsir', 0.08, ['Foggy Forest'], [], False, ['Early']], 
    ['Tauros', 0.06, ['Amp Plains', 'Shimmer Hill'], [], False, ['Early', 'Late']], 
    ['Magikarp', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Gyarados', -0.05, ['Bottomless Sea'], ['Magikarp', 20, False], False, ['Late']], 
    ['Lapras', 0.07, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Ditto', 0.08, ['Sky Stairway'], [], False, ['Late']], 
    ['Eevee', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Vaporeon', -0.12, ['Lake Afar'], ['Eevee', True], False, ['Late']], 
    ['Jolteon', -0.12, ['Spacial Rift'], ['Eevee', True], False, ['Late']], 
    ['Flareon', -0.12, [''], ['Eevee', True], False, ['']], 
    ['Porygon', 0.06, ['Spacial Rift'], [], False, ['Late']], 
    ['Omanyte', 0.06, ['Brine Cave', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Omastar', -0.05, [], ['Omanyte', 40, False], False, []], 
    ['Kabuto', 0.06, ['Marine Resort', 'Final Maze'], [], False, ['Late', 'Late']], 
    ['Kabutops', 0.01, ['Marine Resort'], ['Kabuto', 40, False], False, ['Late']], 
    ['Aerodactyl', 0.08, ['Mt. Horn', 'Mt. Mistral'], [], False, ['Early', 'Late']], 
    ['Snorlax', -0.12, ['Mystery Jungle'], [], False, ['Late']], 
    ['Articuno', 0.5, ['Articuno'], [], False, ['Late']], 
    ['Zapdos', 0.1, ['Amp Plains'], [], True, ['Early']], 
    ['Moltres', 0.3, ['Giant Volcano'], [], True, ['Late']], 
    ['Dratini', 0.08, ['Craggy Coast', 'Marine Resort'], [], False, ['Early', 'Late']], 
    ['Dragonair', -0.05, ['Brine Cave'], ['Dratini', 30, False], False, ['Early']], 
    ['Dragonite', -0.1, [], ['Dragonair', 55, False], False, []], 
    ['Mewtwo', 1.0, ['Sky Stairway'], [], True, ['Late']], 
    ['Mew', 0.5, ['Mew'], [], False, ['Late']], 
    ['Chikorita', 0.08, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Bayleef', -0.1, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Chikorita', 16, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Meganium', -0.12, ['Mystery Jungle'], ['Bayleef', 32, False], False, ['Late']], 
    ['Cyndaquil', 0.08, [''], [], False, ['']], 
    ['Quilava', -0.1, ['Giant Volcano'], ['Cyndaquil', 14, False], False, ['Late']], 
    ['Typhlosion', -0.12, [], ['Quilava', 36, False], False, []], 
    ['Totodile', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Croconaw', -0.1, ['Lake Afar'], ['Totodile', 18, False], False, ['Late']], 
    ['Feraligatr', -0.12, ['Lake Afar'], ['Croconaw', 30, False], False, ['Late']], 
    ['Sentret', 0.06, ['Mt. Travail', 'Shimmer Hill'], [], False, ['Late', 'Late']], 
    ['Furret', -0.05, ['6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Sentret', 15, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Hoothoot', 0.06, ['Foggy Forest'], [], False, ['Early']], 
    ['Noctowl', -0.1, ['Foggy Forest'], ['Hoothoot', 20, False], False, ['Early']], 
    ['Ledyba', 0.08, ['Mt. Travail', 'Midnight Forest'], [], False, ['Late', 'Late']], 
    ['Ledian', -0.05, ['Mt. Travail', 'Midnight Forest'], ['Ledyba', 18, False], False, ['Late', 'Late']], 
    ['Spinarak', 0.06, ['Mt. Bristle', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Ariados', 0.01, ['Mt. Horn'], ['Spinarak', 22, False], False, ['Early']], 
    ['Crobat', -0.12, ['Aegis Cave'], ['Golbat', True], False, ['Late']], 
    ['Chinchou', 0.08, ['Miracle Sea'], [], False, ['Late']], 
    ['Lanturn', -0.05, ['Miracle Sea'], ['Chinchou', 27, False], False, ['Late']], 
    ['Pichu', 0.05, ['Amp Plains'], [], False, ['Early']], 
    ['Cleffa', 0.08, ['Marine Resort'], [], False, ['Late']], 
    ['Igglybuff', 0.08, ['Marine Resort'], [], False, ['Late']], 
    ['Togepi', 0.06, ['Happy Outlook'], [], False, ['Late']], 
    ['Togetic', -0.12, ['Happy Outlook'], ['Togepi', True], False, ['Late']], 
    ['Natu', 0.08, ['Mt. Horn'], [], False, ['Early']], 
    ['Xatu', -0.05, ['Spacial Rift'], ['Natu', 25, False], False, ['Late']], 
    ['Mareep', 0.08, ['Amp Plains', 'Shimmer Hill', 'Final Maze'], [], False, ['Early', 'Late', 'Late']], 
    ['Flaaffy', 0.01, ['Amp Plains'], ['Mareep', 15, False], False, ['Early']], 
    ['Ampharos', -0.05, ['Landslide Cave', 'Amp Plains'], ['Flaaffy', 30, False], False, ['Early', 'Early']], 
    ['Bellossom', -0.05, ['Marine Resort'], ['Gloom', True], False, ['Late']], 
    ['Marill', 0.01, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Azurill', True], False, ['Late', 'Late', 'Late']], 
    ['Azumarill', 0.01, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Marill', 18, False], False, ['Late', 'Late', 'Late']], 
    ['Sudowoodo', 0.01, ['Shimmer Desert'], [], False, ['Late']], 
    ['Politoed', -0.12, ['Lake Afar'], ['Poliwhirl', True], False, ['Late']], 
    ['Hoppip', 0.08, ['Apple Woods', 'Oran Forest'], [], False, ['Early', 'Early']], 
    ['Skiploom', 0.01, ['Foggy Forest', 'Lush Prairie', 'Tiny Meadow'], ['Hoppip', 18, False], False, ['Early', 'Early', 'Early']], 
    ['Jumpluff', -0.1, ['Mt. Mistral', 'Sky Stairway'], ['Skiploom', 27, False], False, ['Late', 'Late']], 
    ['Aipom', 0.06, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Sunkern', 0.05, ['Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Sunflora', -0.12, ['Happy Outlook', 'Mystery Jungle'], ['Sunkern', True], False, ['Late', 'Late']], 
    ['Yanma', 0.08, ['Steam Cave', 'Steam Cave', 'Lush Prairie'], [], False, ['Early', 'Early', 'Early']], 
    ['Wooper', 0.08, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']], 
    ['Quagsire', 0.01, ['Lake Afar'], ['Wooper', 20, False], False, ['Late']], 
    ['Espeon', -0.12, ['Marine Resort', 'Shimmer Hill'], ['Eevee', True], False, ['Late', 'Late']], 
    ['Umbreon', -0.12, ['Concealed Ruins', 'World Abyss'], ['Eevee', True], False, ['Late', 'Late']], 
    ['Murkrow', 0.06, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']], 
    ['Slowking', -0.12, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Slowpoke', True], False, ['Late', 'Late', 'Late']], 
    ['Misdreavus', 0.08, ['Sky Stairway', 'Final Maze'], [], False, ['Late', 'Late']], 
    ['Unown', 0.08, ['Aegis Cave'], [], False, ['Late']], 
    ['Wobbuffet', -0.12, ['Marine Resort'], ['Wynaut', 15, False], False, ['Late']], 
    ['Girafarig', 0.06, ['Amp Plains', 'Shimmer Hill'], [], False, ['Early', 'Late']], 
    ['Pineco', 0.08, ['Mt. Horn'], [], False, ['Early']], 
    ['Forretress', 0.01, ['Sky Stairway'], ['Pineco', 31, False], False, ['Late']], 
    ['Dunsparce', 0.06, ['Foggy Forest'], [], False, ['Early']], 
    ['Gligar', 0.08, ['Spacial Rift'], [], False, ['Late']], 
    ['Steelix', -0.1, ['Sky Stairway'], ['Onix', True], False, ['Late']], 
    ['Snubbull', 0.06, ['Steam Cave', 'Marine Resort'], [], False, ['Early', 'Late']], 
    ['Granbull', 0.01, ['Steam Cave', 'Landslide Cave'], ['Snubbull', 23, False], False, ['Early', 'Early']], 
    ['Qwilfish', 0.07, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']],
    ['Scizor', -0.12, ['Mt. Travail'], ['Scyther', True], False, ['Late']], 
    ['Shuckle', 0.08, ['Steam Cave', 'Landslide Cave'], [], False, ['Early', 'Early']], 
    ['Heracross', 0.06, ['Mt. Travail'], [], False, ['Late']], 
    ['Sneasel', 0.06, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Teddiursa', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Ursaring', -0.12, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail', 'Shimmer Hill'], ['Teddiursa', 30, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Slugma', 0.08, ['Steam Cave', 'Giant Volcano'], [], False, ['Early', 'Late']], 
    ['Magcargo', 0.01, [''], ['Slugma', 38, False], False, ['']], 
    ['Swinub', 0.08, ['Crevice Cave', 'Final Maze'], [], False, ['Late', 'Late']], 
    ['Piloswine', -0.12, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Swinub', 33, False], False, ['Late', 'Late', 'Late']], 
    ['Corsola', 0.08, ['Marine Resort'], [], False, ['Late']], 
    ['Remoraid', 0.08, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Octillery', -0.12, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Delibird', 0.08, ['Blizzard Island', 'Crevice Cave'], [], False, ['Late', 'Late']], 
    ['Mantine', 0.08, ['Miracle Sea'], ['Mantyke', True], False, ['Late']], 
    ['Skarmory', 0.08, ['Sky Stairway'], [], False, ['Late']], 
    ['Houndour', 0.08, ['Shimmer Hill', 'Final Maze'], [], False, ['Late', 'Late']], 
    ['Houndoom', -0.05, ['Treeshroud Forest'], ['Houndour', 24, False], False, ['Early']], 
    ['Kingdra', -0.12, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], ['Seadra', True], False, ['Late', 'Late', 'Late']], 
    ['Phanpy', 0.08, ['Amp Plains', 'Marine Resort', 'Final Maze'], [], False, ['Early', 'Late', 'Late']], 
    ['Donphan', 0.01, ['Crystal Cave'], ['Phanpy', 25, False], False, ['Early']], 
    ['Porygon2', 0.05, [], ['Porygon', True], False, []], 
    ['Stantler', 0.06, ['Foggy Forest', 'Shimmer Hill'], [], False, ['Early', 'Late']], 
    ['Smeargle', 0.07, ['Foggy Forest', 'Marine Resort'], [], False, ['Early', 'Late']], 
    ['Tyrogue', 0.06, ['Mt. Travail', 'Marine Resort'], [], False, ['Late', 'Late']], 
    ['Hitmontop', -0.12, ['Lost Wilderness'], ['Tyrogue', 20, True], False, ['Late']], 
    ['Smoochum', 0.06, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Elekid', 0.08, ['Amp Plains'], [], False, ['Early']], 
    ['Magby', 0.08, ['Steam Cave', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Miltank', 0.08, ['Marine Resort', 'Shimmer Hill'], [], False, ['Late', 'Late']], 
    ['Blissey', -0.12, ['Happy Outlook'], ['Chansey', True], False, ['Late']], 
    ['Raikou', 1.0, ['Southeastern Islands'], [], True, ['Late']], 
    ['Entei', 1.0, ['Inferno Cave'], [], True, ['Late']], 
    ['Suicune', 1.0, ['Treacherous Waters'], [], True, ['Late']], 
    ['Larvitar', 0.08, ['Northern Desert'], [], False, ['Early']], 
    ['Pupitar', 0.01, ['Quicksand Cave'], ['Larvitar', 30, False], False, ['Early']], 
    ['Tyranitar', -0.12, ['Quicksand Cave'], ['Pupitar', 55, False], False, ['Early']], 
    ['Lugia', 0.1, ['Surrounded Sea'], [], True, ['Late']], 
    ['Ho-Oh', 0.1, ['Mt. Mistral'], [], True, ['Late']], 
    ['Celebi', 0.2, ['Mystifying Forest', 'Celebi'], [], True, ['Late', 'Late']], 
    ['Treecko', 0.08, ['Mystery Jungle'], [], False, ['Late']], 
    ['Grovyle', -0.1, ['Mystery Jungle'], ['Treecko', 16, False], False, ['Late']], 
    ['Sceptile', -0.12, ['Mystery Jungle'], ['Grovyle', 36, False], False, ['Late']], 
    ['Torchic', 0.08, ['Giant Volcano'], [], False, ['Late']], 
    ['Combusken', -0.1, ['Giant Volcano'], ['Torchic', 16, False], False, ['Late']], 
    ['Blaziken', -0.12, [], ['Combusken', 36, False], False, []], 
    ['Mudkip', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Marshtomp', -0.1, ['Lake Afar'], ['Mudkip', 16, False], False, ['Late']], 
    ['Swampert', -0.12, ['Lake Afar'], ['Marshtomp', 36, False], False, ['Late']], 
    ['Poochyena', 0.08, ['Concealed Ruins', 'World Abyss', 'Final Maze'], [], False, ['Late', 'Late', 'Late']], 
    ['Mightyena', -0.05, ['Concealed Ruins', 'World Abyss'], ['Poochyena', 18, False], False, ['Late', 'Late']], 
    ['Zigzagoon', 0.08, ['Foggy Forest'], [], False, ['Early']], 
    ['Linoone', 0.01, ['Shimmer Hill'], ['Zigzagoon', 20, False], False, ['Late']], 
    ['Wurmple', 0.06, ['Oran Forest', 'Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Early', 'Late', 'Late', 'Late']], 
    ['Silcoon', -0.1, ['Lush Prairie', 'Mystery Jungle'], ['Wurmple', 7, False], False, ['Early', 'Late']], 
    ['Beautifly', 0.01, ['Mt. Horn', 'Lush Prairie', 'Midnight Forest'], ['Silcoon', 10, False], False, ['Early', 'Early', 'Late']], 
    ['Cascoon', -0.1, ['Mt. Horn', 'Lush Prairie', 'Mystery Jungle'], ['Wurmple', 7, False], False, ['Early', 'Early', 'Late']], 
    ['Dustox', 0.01, ['Landslide Cave'], ['Cascoon', 10, False], False, ['Early']], 
    ['Lotad', 0.06, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']], 
    ['Lombre', -0.05, ['Lake Afar'], ['Lotad', 14, False], False, ['Late']], 
    ['Ludicolo', -0.12, ['Lake Afar'], ['Lombre', True], False, ['Late']], 
    ['Seedot', 0.08, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Nuzleaf', 0.01, ['Mystifying Forest', 'Midnight Forest', 'Mystery Jungle'], ['Seedot', 14, False], False, ['Late', 'Late', 'Late']], 
    ['Shiftry', -0.12, ['Lost Wilderness'], ['Nuzleaf', True], False, ['Late']], 
    ['Taillow', 0.06, ['Concealed Ruins', 'World Abyss'], [], False, ['Late', 'Late']], 
    ['Swellow', 0.01, ['Concealed Ruins', 'Mt. Mistral', 'World Abyss'], ['Taillow', 22, False], False, ['Late', 'Late', 'Late']], 
    ['Wingull', 0.06, ['Craggy Coast', 'Marine Resort'], [], False, ['Early', 'Late']], 
    ['Pelipper', -0.12, ['Brine Cave', 'Marine Resort'], ['Wingull', 25, False], False, ['Early', 'Late']], 
    ['Ralts', 0.05, ['Treeshroud Forest'], [], False, ['Early']], 
    ['Kirlia', 0.01, ['Treeshroud Forest'], ['Ralts', 20, False], False, ['Early']], 
    ['Gardevoir', -0.1, [], ['Kirlia', 30, False], False, []], 
    ['Surskit', 0.06, ['Waterfall Cave'], [], False, ['Early']], 
    ['Masquerain', -0.1, ['Serenity River'], ['Surskit', 22, False], False, ['Early']], 
    ['Shroomish', 0.06, ['Mt. Horn', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Breloom', 0.01, ['Foggy Forest', 'Tiny Meadow'], ['Shroomish', 23, False], False, ['Early', 'Early']], 
    ['Slakoth', 0.08, ['Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late']], 
    ['Vigoroth', -0.1, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], ['Slakoth', 18, False], False, ['Late', 'Late', 'Late']], 
    ['Slaking', -0.12, ['Crevice Cave', 'Mt. Avalanche'], ['Vigoroth', 36, False], False, ['Late', 'Late']], 
    ['Nincada', 0.06, ['Quicksand Cave', 'Midnight Forest'], [], False, ['Early', 'Late']], 
    ['Ninjask', 0.01, ['Quicksand Cave'], ['Nincada', 20, False], False, ['Early']], 
    ['Shedinja', -0.12, ['8th Station Pass', '9th Station Pass', 'Sky Peak Summit Pass', 'Mt. Travail'], ['Nincada', 20, False], False, ['Late', 'Late', 'Late', 'Late']], 
    ['Whismur', 0.08, ['Marine Resort'], [], False, ['Late']], 
    ['Loudred', -0.1, ['Concealed Ruins', 'World Abyss'], ['Whismur', 20, False], False, ['Late', 'Late']], 
    ['Exploud', -0.12, ['Concealed Ruins', 'World Abyss'], ['Loudred', 40, False], False, ['Late', 'Late']], 
    ['Makuhita', 0.04, ['Lost Wilderness'], [], False, ['Late']], 
    ['Hariyama', -0.12, ['Lost Wilderness'], ['Makuhita', 24, False], False, ['Late']], 
    ['Azurill', 0.08, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Nosepass', 0.06, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Skitty', 0.06, ['Happy Outlook'], [], False, ['Late']], 
    ['Delcatty', -0.12, ['Concealed Ruins', 'World Abyss'], ['Skitty', True], False, ['Late', 'Late']], 
    ['Sableye', 0.08, ['Spacial Rift'], [], False, ['Late']], 
    ['Mawile', 0.06, ['Quicksand Cave', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Aron', 0.06, ['Northern Desert'], [], False, ['Early']], 
    ['Lairon', 0.01, ['Northern Desert'], ['Aron', 32, False], False, ['Early']], 
    ['Aggron', -0.1, [], ['Lairon', 42, False], False, []], 
    ['Meditite', 0.06, ['Mt. Travail', 'Lost Wilderness', 'Final Maze'], [], False, ['Late', 'Late', 'Late']], 
    ['Medicham', -0.12, ['Mt. Travail', 'Lost Wilderness'], ['Meditite', 37, False], False, ['Late', 'Late']], 
    ['Electrike', 0.06, ['Amp Plains'], [], False, ['Early']], 
    ['Manectric', -0.1, [], ['Electrike', 26, False], False, []], 
    ['Plusle', 0.08, ['Amp Plains'], [], False, ['Early']], 
    ['Minun', 0.08, ['Amp Plains'], [], False, ['Early']], 
    ['Volbeat', 0.08, ['Steam Cave'], [], False, ['Early']], 
    ['Illumise', 0.08, ['Steam Cave'], [], False, ['Early']], 
    ['Roselia', 0.06, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Midnight Forest', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Gulpin', 0.07, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Swalot', -0.12, ['Marine Resort'], ['Gulpin', 26, False], False, ['Late']], 
    ['Carvanha', 0.01, ['Surrounded Sea'], [], False, ['Late']], 
    ['Sharpedo', -0.12, ['Miracle Sea'], ['Carvanha', 30, False], False, ['Late']], 
    ['Wailmer', 0.04, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Wailord', -0.12, ['Surrounded Sea', 'Bottomless Sea'], ['Wailmer', 40, False], False, ['Late', 'Late']], 
    ['Numel', 0.06, ['Steam Cave', 'Giant Volcano'], [], False, ['Early', 'Late']], 
    ['Camerupt', -0.12, ['Shimmer Hill', 'Giant Volcano'], ['Numel', 33, False], False, ['Late', 'Late']], 
    ['Torkoal', 0.06, [], [], False, []], 
    ['Spoink', 0.06, ['Marine Resort'], [], False, ['Late']], 
    ['Grumpig', -0.1, [], ['Spoink', 32, False], False, []], 
    ['Spinda', 0.06, ['Marine Resort', 'Lost Wilderness'], [], False, ['Late', 'Late']], 
    ['Trapinch', 0.08, ['Northern Desert'], [], False, ['Early']], 
    ['Vibrava', 0.01, ['Quicksand Cave'], ['Trapinch', 35, False], False, ['Early']], 
    ['Flygon', -0.12, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mt. Mistral', 'Mystery Jungle'], ['Vibrava', 45, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Cacnea', 0.06, ['Northern Desert'], [], False, ['Early']], 
    ['Cacturne', 0.01, ['Northern Desert', 'Happy Outlook'], ['Cacnea', 32, False], False, ['Early', 'Late']], 
    ['Swablu', 0.06, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Altaria', -0.12, ['Crevice Cave', 'Mt. Avalanche'], ['Swablu', 35, False], False, ['Late', 'Late']], 
    ['Zangoose', 0.06, ['Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late']], 
    ['Seviper', 0.06, ['Crystal Cave'], [], False, ['Early']], 
    ['Lunatone', 0.06, ['Spacial Rift'], [], False, ['Late']], 
    ['Solrock', 0.06, ['Spacial Rift'], [], False, ['Late']], 
    ['Barboach', 0.08, ['Waterfall Cave', 'Serenity River'], [], False, ['Early', 'Early']], 
    ['Whiscash', 0.01, ['Waterfall Cave'], ['Barboach', 30, False], False, ['Early']], 
    ['Corphish', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Crawdaunt', -0.12, ['Lake Afar'], ['Corphish', 30, False], False, ['Late']], 
    ['Baltoy', 0.06, ['Northern Desert'], [], False, ['Early']], 
    ['Claydol', 0.01, ['Sky Stairway'], ['Baltoy', 36, False], False, ['Late']], 
    ['Lileep', 0.06, ['Drenched Bluff'], [], False, ['Early']], 
    ['Cradily', -0.05, ['Miracle Sea'], ['Lileep', 40, False], False, ['Late']], 
    ['Anorith', 0.08, ['Drenched Bluff'], [], False, ['Early']], 
    ['Armaldo', -0.05, ['Mt. Avalanche'], ['Anorith', 40, False], False, ['Late']], 
    ['Feebas', 0.08, ['Lake Afar'], [], False, ['Late']], 
    ['Milotic', -0.12, ['Lake Afar'], ['Feebas', True], False, ['Late']], 
    ['Castform', 0.06, ['Blizzard Island', 'Shimmer Hill'], [], False, ['Late', 'Late']], 
    ['Kecleon', -0.5, [], [], True, []], 
    ['Shuppet', 0.06, ['Concealed Ruins'], [], False, ['Late']], 
    ['Banette', -0.1, ['Sky Stairway'], ['Shuppet', 37, False], False, ['Late']], 
    ['Duskull', 0.06, ['Sky Stairway'], [], False, ['Late']], 
    ['Dusclops', -0.1, [], ['Duskull', 37, False], False, []], 
    ['Tropius', 0.06, ['Spacial Rift'], [], False, ['Late']], 
    ['Chimecho', 0.07, ['Spacial Rift'], ['Chingling', True], False, ['Late']], 
    ['Absol', 0.07, ['Crystal Crossing'], [], False, ['Early']], 
    ['Wynaut', 0.08, ['Marine Resort'], [], False, ['Late']], 
    ['Snorunt', 0.06, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Glalie', 0.01, ['Crystal Crossing'], ['Snorunt', 42, False], False, ['Early']], 
    ['Spheal', 0.08, ['Craggy Coast'], [], False, ['Early']], 
    ['Sealeo', 0.01, ['Craggy Coast'], ['Spheal', 32, False], False, ['Early']], 
    ['Walrein', 0.01, ['Brine Cave'], ['Sealeo', 44, False], False, ['Early']], 
    ['Clamperl', 0.08, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Huntail', -0.12, ['Miracle Sea'], ['Clamperl', True], False, ['Late']], 
    ['Gorebyss', -0.12, ['Miracle Sea'], ['Clamperl', True], False, ['Late']], 
    ['Relicanth', 0.06, ['Miracle Sea'], [], False, ['Late']], 
    ['Luvdisc', 0.08, ['Miracle Sea'], [], False, ['Late']], 
    ['Bagon', 0.06, ['Crystal Crossing', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Shelgon', 0.01, ['Sky Stairway'], ['Bagon', 30, False], False, ['Late']], 
    ['Salamence', -0.1, [], ['Shelgon', 50, False], False, []], 
    ['Beldum', 0.06, ['Crystal Cave'], [], False, ['Early']], 
    ['Metang', 0.01, ['Sky Stairway'], ['Beldum', 20, False], False, ['Late']], 
    ['Metagross', -0.1, [], ['Metang', 45, False], False, []], 
    ['Regirock', 0.5, ['Regirock'], [], False, ['Late']], 
    ['Regice', 0.5, ['Regice'], [], False, ['Late']], 
    ['Registeel', 0.5, ['Registeel'], [], False, ['Late']], 
    ['Latias', 0.0, ['Spacial Rift', 'Happy Outlook'], [], True, ['Late', 'Late']], 
    ['Latios', 0.0, ['Spacial Rift', 'Midnight Forest'], [], True, ['Late', 'Late']], 
    ['Kyogre', 0.5, ['Kyogre'], [], False, ['Late']], 
    ['Groudon', 0.5, ['Groudon'], [], False, ['Late']], 
    ['Rayquaza', 0.5, ['Rayquaza'], [], False, ['Late']], 
    ['Jirachi', 1.0, [], [], True, []], 
    ['Deoxys', -0.1, ['Shimmer Hill'], [], True, ['Late']], 
    ['Turtwig', 0.08, ['Mystifying Forest', 'Happy Outlook', 'Mystery Jungle'], [], False, ['Late', 'Late', 'Late']], 
    ['Grotle', -0.1, ['Mystifying Forest', 'Mystery Jungle'], ['Turtwig', 18, False], False, ['Late', 'Late']], 
    ['Torterra', -0.12, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', 'Mystery Jungle'], ['Grotle', 32, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Chimchar', 0.08, ['Giant Volcano'], [], False, ['Late']], 
    ['Monferno', -0.1, ['Giant Volcano'], ['Chimchar', 14, False], False, ['Late']], 
    ['Infernape', -0.12, [], ['Monferno', 36, False], False, []], 
    ['Piplup', 0.08, ['Blizzard Island', 'Crevice Cave', 'Mt. Avalanche'], [], False, ['Late', 'Late', 'Late']], 
    ['Prinplup', -0.1, ['Crevice Cave', 'Mt. Avalanche'], ['Piplup', 16, False], False, ['Late', 'Late']], 
    ['Empoleon', -0.12, ['Crevice Cave', 'Mt. Avalanche'], ['Prinplup', 36, False], False, ['Late', 'Late']], 
    ['Starly', 0.08, ['Mt. Bristle', 'Oran Forest'], [], False, ['Early', 'Early']], 
    ['Staravia', 0.08, ['Tiny Meadow', 'Final Maze'], ['Starly', 14, False], False, ['Early', 'Late']], 
    ['Staraptor', 0.02, ['Mt. Mistral'], ['Staravia', 34, False], False, ['Late']], 
    ['Bidoof', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Bibarel', 0.04, ['4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', '9th Station Pass', 'Mt. Travail'], ['Bidoof', 15, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Kricketot', 0.08, ['Mystifying Forest'], [], False, ['Late']], 
    ['Kricketune', 0.05, ['Steam Cave', 'Steam Cave'], ['Kricketot', 10, False], False, ['Early', 'Early']], 
    ['Shinx', 0.08, ['Amp Plains'], [], False, ['Early']], 
    ['Luxio', 0.01, ['Amp Plains'], ['Shinx', 15, False], False, ['Early']], 
    ['Luxray', -0.12, ['Amp Plains'], ['Luxio', 30, False], False, ['Early']], 
    ['Budew', 0.08, ['Apple Woods', 'Oran Forest', 'Happy Outlook'], [], False, ['Early', 'Early', 'Late']], 
    ['Roserade', -0.12, ['Mystery Jungle'], ['Roselia', True], False, ['Late']], 
    ['Cranidos', 0.08, ['Crystal Cave'], [], False, ['Early']], 
    ['Rampardos', 0.02, [], ['Cranidos', 30, False], False, []], 
    ['Shieldon', 0.08, ['Crystal Cave'], [], False, ['Early']], 
    ['Bastiodon', 0.02, [], ['Shieldon', 30, False], False, []], 
    ['Burmy-Sand', 0.08, ['Apple Woods'], [], False, ['Early']], 
    ['Burmy-Plant', 0.08, ['Lush Prairie'], [], False, ['Early']], 
    ['Burmy-Trash', 0.08, ['Oran Forest'], [], False, ['Early']], 
    ['Wormadam-Sand', 0.08, ['Crystal Cave'], ['Burmy-Sand', 20, True], False, ['Early']], 
    ['Wormadam-Plant', 0.08, ['Crystal Crossing'], ['Burmy-Sand', 20, True], False, ['Early']], 
    ['Wormadam-Trash', 0.08, ['Landslide Cave'], ['Burmy-Sand', 20, True], False, ['Early']], 
    ['Mothim', 0.08, ['Mt. Mistral', 'Sky Stairway'], ['Burmy', 20, True], False, ['Late', 'Late']], 
    ['Combee', 0.06, ['Apple Woods'], [], False, ['Early']], 
    ['Vespiquen', -0.05, ['Treeshroud Forest'], ['Combee', 21, True], False, ['Early']], 
    ['Pachirisu', 0.08, ['Foggy Forest'], [], False, ['Early']], 
    ['Buizel', 0.08, ['Marine Resort'], [], False, ['Late']], 
    ['Floatzel', 0.01, ['Crystal Crossing'], ['Buizel', 26, False], False, ['Early']], 
    ['Cherubi', 0.08, ['Foggy Forest'], [], False, ['Early']], 
    ['Cherrim', 0.02, ['Treeshroud Forest'], ['Cherubi', 25, False], False, ['Early']], 
    ['Shellos-East', 0.06, ['Miracle Sea'], [], False, ['Late']], 
    ['Shellos-West', 0.06, ['Drenched Bluff'], [], False, ['Early']], 
    ['Gastrodon-East', 0.08, ['Craggy Coast'], ['Shellos-East', 30, False], False, ['Early']], 
    ['Gastrodon-West', 0.08, ['Brine Cave'], ['Shellos-West', 30, False], False, ['Early']], 
    ['Ambipom', 0.08, ['Marine Resort', 'Sky Stairway'], [], False, ['Late', 'Late']], 
    ['Drifloon', 0.03, ['Sky Stairway'], [], False, ['Late']], 
    ['Drifblim', 0.03, ['Mt. Mistral'], ['Drifloon', 28, False], False, ['Late']], 
    ['Buneary', 0.08, ['Foggy Forest'], [], False, ['Early']], 
    ['Lopunny', -0.12, ['Mystery Jungle'], ['Buneary', True], False, ['Late']], 
    ['Mismagius', 0.08, ['Mt. Mistral'], ['Misdreavus', True], False, ['Late']], 
    ['Honchkrow', -0.12, ['Spacial Rift'], ['Murkrow', True], False, ['Late']], 
    ['Glameow', 0.08, ['Crystal Crossing'], [], False, ['Early']], 
    ['Purugly', -0.1, [], ['Glameow', 38, False], False, []], 
    ['Chingling', 0.08, ['Drenched Bluff'], [], False, ['Early']], 
    ['Stunky', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Skuntank', 0.01, ['Mystifying Forest', '1st Station Pass', '2nd Station Pass', '3rd Station Pass', '4th Station Pass', '5th Station Pass', '6th Station Pass', '7th Station Pass', '8th Station Pass', 'Shimmer Hill', 'Mystery Jungle'], ['Stunky', 34, False], False, ['Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Bronzor', 0.08, ['Spacial Rift'], [], False, ['Late']], 
    ['Bronzong', 0.02, [], ['Bronzor', 33, False], False, []], 
    ['Bonsly', 0.08, ['Mt. Horn'], [], False, ['Early']], 
    ['Mime Jr.', 0.08, ['Happy Outlook'], [], False, ['Late']], 
    ['Happiny', 0.08, ['Happy Outlook'], [], False, ['Late']], 
    ['Chatot', -0.1, ['Spacial Rift'], [], False, ['Late']], 
    ['Spiritomb', -0.1, ['Spacial Rift', 'Sky Stairway'], [], False, ['Late', 'Late']], 
    ['Gible', 0.08, ['Landslide Cave'], [], False, ['Early']], 
    ['Gabite', 0.08, ['Sky Stairway'], ['Gible', 24, False], False, ['Late']], 
    ['Garchomp', 0.01, ['Shimmer Desert'], ['Gabite', 48, False], False, ['Late']], 
    ['Munchlax', 0.08, ['Mystifying Forest', 'Mystery Jungle'], [], False, ['Late', 'Late']], 
    ['Riolu', 0.08, ['Crystal Cave'], [], False, ['Early']], 
    ['Lucario', -0.1, ['Lost Wilderness'], ['Riolu', True], False, ['Late']], 
    ['Hippopotas', 0.08, ['Quicksand Cave'], [], False, ['Early']], 
    ['Hippowdon', 0.08, [], ['Hippopotas', 34, False], False, []], 
    ['Skorupi', 0.08, ['Quicksand Cave', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Drapion', -0.12, ['Spacial Rift'], ['Skorupi', 40, False], False, ['Late']], 
    ['Croagunk', 0.08, ['Marine Resort', 'Lost Wilderness'], [], False, ['Late', 'Late']], 
    ['Toxicroak', -0.12, ['Spacial Rift'], ['Croagunk', 37, False], False, ['Late']], 
    ['Carnivine', 0.08, ['Northern Desert', 'Final Maze'], [], False, ['Early', 'Late']], 
    ['Finneon', 0.08, ['Surrounded Sea', 'Miracle Sea', 'Bottomless Sea'], [], False, ['Late', 'Late', 'Late']], 
    ['Lumineon', 0.08, ['Miracle Sea'], ['Finneon', 31, False], False, ['Late']], 
    ['Mantyke', 0.08, ['Miracle Sea'], [], False, ['Late']], 
    ['Snover', 0.08, ['Crevice Cave'], [], False, ['Late']], 
    ['Abomasnow', -0.1, [], ['Snover', 40, False], False, []], 
    ['Weavile', -0.12, ['Crevice Cave', 'Mt. Avalanche'], ['Sneasel', True], False, ['Late', 'Late']], 
    ['Magnezone', -0.12, ['Spacial Rift'], ['Magneton', True], False, ['Late']], 
    ['Lickilicky', -0.12, ['Marine Resort'], ['Lickitung', 33, True], False, ['Late']], 
    ['Rhyperior', -0.12, ['Shimmer Desert'], ['Rhydon', True], False, ['Late']], 
    ['Tangrowth', 0.08, ['Sky Stairway'], ['Tangela', 33, True], False, ['Late']], 
    ['Electivire', -0.12, ['Spacial Rift'], ['Electabuzz', True], False, ['Late']], 
    ['Magmortar', -0.1, [], ['Magmar', True], False, []], 
    ['Togekiss', -0.12, ['Sky Stairway'], ['Togetic', True], False, ['Late']], 
    ['Yanmega', -0.05, ['Amp Plains'], ['Yanma', 33, True], False, ['Early']], 
    ['Leafeon', -0.1, ['Sky Stairway'], ['Eevee', True], False, ['Late']], 
    ['Glaceon', -0.1, ['Crevice Cave'], ['Eevee', True], False, ['Late']], 
    ['Gliscor', -0.05, ['Mt. Mistral', 'Sky Stairway'], ['Gligar', True], False, ['Late', 'Late']], 
    ['Mamoswine', -0.12, ['Crevice Cave', 'Mt. Avalanche'], ['Pilowswine', 1, True], False, ['Late', 'Late']], 
    ['Porygon-Z', -0.05, [], ['Porygon2', True], False, []], 
    ['Gallade', -0.12, ['Spacial Rift'], ['Kirlia', True], False, ['Late']], 
    ['Probopass', 0.08, ['Sky Stairway'], ['Nosepass', True], False, ['Late']], 
    ['Dusknoir', -0.12, ['Spacial Rift', 'Sky Stairway'], ['Dusclops', True], False, ['Late', 'Late']], 
    ['Froslass', -0.1, ['Crystal Crossing'], ['Snorunt', True], False, ['Early']], 
    ['Rotom', -0.12, ['Midnight Forest'], [], False, ['Late']], 
    ['Uxie', 1.0, ['Uxie'], [], False, ['Late']], 
    ['Mesprit', 1.0, ['Mesprit'], [], False, ['Late']], 
    ['Azelf', 1.0, ['Azelf'], [], False, ['Late']], 
    ['Dialga', 1.0, ['Dialga'], [], False, ['Late']], 
    ['Palkia', 1.0, ['Palkia'], [], False, ['Late']], 
    ['Heatran', 0.5, ['Heatran'], [], False, ['Late']], 
    ['Regigigas', 1.0, ['Regigigas'], [], False, ['Late']], 
    ['Giratina', 0.5, ['Giratina'], [], False, ['Late']], 
    ['Cresselia', 1.0, ['Cresselia'], [], False, ['Late']], 
    ['Phione', 1.0, ['Phione'], [], False, ['Late']], 
    ['Manaphy', 1.0, ['Manaphy'], [], False, ['Late']], 
    ['Darkrai', -0.22, ['Mystifying Forest', 'Crevice Cave', 'Miracle Sea', 'Mt. Travail', 'Spacial Rift'], [], True, ['Late', 'Late', 'Late', 'Late', 'Late']], 
    ['Shaymin', 1.0, ['Shaymin'], [], False, ['Late']]
    ]

dungeon_location = {
    "Beach Cave" : "Early",
    "Drenched Bluff" : "Early",
    "Mt. Bristle" : "Early",
    "Waterfall Cave" : "Early",
    "Apple Woods" : "Early",
    "Craggy Coast" : "Early",
    "Mt. Horn" : "Early",
    "Foggy Forest" : "Early",
    "Steam Cave" : "Early",
    "Amp Plains" : "Early",
    "Northern Desert" : "Early",
    "Quicksand Cave" : "Early",
    "Crystal Cave" : "Early",
    "Crystal Crossing" : "Early",
    "Chasm Cave" : "Early",
    "Dark Hill" : "Early",
    "Sealed Ruin" : "Early",
    "Dusk Forest" : "Early",
    "Deep Dusk Forest" : "Early",
    "Treeshroud Forest" : "Early",
    "Brine Cave" : "Early",
    "Hidden Land" : "Late",
    "Temporal Tower" : "Late",
    "Mystifying Forest" : "Late",
    "1st Station Pass" : "Late",
    "2nd Station Pass" : "Late",
    "3rd Station Pass" : "Late",
    "4th Station Pass" : "Late",
    "5th Station Pass" : "Late",
    "6th Station Pass" : "Late",
    "7th Station Pass" : "Late",
    "8th Station Pass" : "Late",
    "9th Station Pass" : "Late",
    "Sky Peak Summit Pass" : "Late",
    "Blizzard Island" : "Late",
    "Crevice Cave" : "Late",
    "Surrounded Sea" : "Late",
    "Miracle Sea" : "Late",
    "Aegis Cave" : "Late",
    "Mt. Travail" : "Late",
    "The Nightmare" : "Late",
    "Spacial Rift" : "Late",
    "Side Path" : "Early",
    "Rock Path" : "Early",
    "Forest Path" : "Early",
    "Oran Forest" : "Early",
    "Tiny Meadow" : "Early",
    "Lush Prairie" : "Early",
    "Labyrinth Cave" : "Early",
    "Serenity River" : "Early",
    "Landslide Cave" : "Early",
    "Lake Afar" : "Late",
    "Happy Outlook" : "Late",
    "Mt. Mistral" : "Late",
    "Shimmer Hill" : "Late",
    "Lost Wilderness" : "Late",
    "Midnight Forest" : "Late",
    "Bottomless Sea" : "Late",
    "Shimmer Desert" : "Late",
    "Mt. Avalanche" : "Late",
    "Giant Volcano" : "Late",
    "World Abyss" : "Late",
    "Sky Stairway" : "Late",
    "Star Cave" : "Late",
    "Mystery Jungle" : "Late",
    "Concealed Ruins" : "Late",
    "Marine Resort" : "Late",
    "Zero Isle North" : "Late",
    "Zero Isle East" : "Late",
    "Zero Isle West" : "Late",
    "Zero Isle South" : "Late",
    "Zero Isle Center" : "Late",
    "Final Maze" : "Late",
    "Destiny Tower" : "Late",
    "Oblivion Forest" : "Late",
    "Treacherous Waters" : "Late",
    "Southeastern Islands" : "Late",
    "Inferno Cave" : "Late",
    "Lust Prairie" : "Early",
    "Articuno" : "Late",
    "Mew" : "Late",
    "Celebi" : "Late",
    "Regirock" : "Late",
    "Regice" : "Late",
    "Registeel" : "Late",
    "Kyogre" : "Late",
    "Groudon" : "Late",
    "Rayquaza" : "Late",
    "Uxie" : "Late",
    "Azelf" : "Late",
    "Mesprit" : "Late",
    "Dialga" : "Late",
    "Palkia" : "Late",
    "Heatran" : "Late",
    "Cresselia" : "Late",
    "Regigigas" : "Late",
    "Giratina" : "Late",
    "Phione" : "Late",
    "Manaphy" : "Late",
    "Shaymin" : "Late",
    "" : ""
}